/*
Eon API

The Eon.io REST API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eon

import (
	"encoding/json"
)

// checks if the UpdateAwsSourceAccountAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateAwsSourceAccountAttributes{}

// UpdateAwsSourceAccountAttributes Updatable AWS account fields. Applicable when the source account's cloud provider is `AWS`. 
type UpdateAwsSourceAccountAttributes struct {
	// ARN of the role Eon assumes to access the account in AWS. Only the role name portion of the ARN can be changed; the AWS account ID must remain the same. To use a different AWS account, disconnect and connect a new source account. 
	RoleArn NullableString `json:"roleArn,omitempty"`
}

// NewUpdateAwsSourceAccountAttributes instantiates a new UpdateAwsSourceAccountAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateAwsSourceAccountAttributes() *UpdateAwsSourceAccountAttributes {
	this := UpdateAwsSourceAccountAttributes{}
	return &this
}

// NewUpdateAwsSourceAccountAttributesWithDefaults instantiates a new UpdateAwsSourceAccountAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateAwsSourceAccountAttributesWithDefaults() *UpdateAwsSourceAccountAttributes {
	this := UpdateAwsSourceAccountAttributes{}
	return &this
}

// GetRoleArn returns the RoleArn field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateAwsSourceAccountAttributes) GetRoleArn() string {
	if o == nil || IsNil(o.RoleArn.Get()) {
		var ret string
		return ret
	}
	return *o.RoleArn.Get()
}

// GetRoleArnOk returns a tuple with the RoleArn field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateAwsSourceAccountAttributes) GetRoleArnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RoleArn.Get(), o.RoleArn.IsSet()
}

// HasRoleArn returns a boolean if a field has been set.
func (o *UpdateAwsSourceAccountAttributes) HasRoleArn() bool {
	if o != nil && o.RoleArn.IsSet() {
		return true
	}

	return false
}

// SetRoleArn gets a reference to the given NullableString and assigns it to the RoleArn field.
func (o *UpdateAwsSourceAccountAttributes) SetRoleArn(v string) {
	o.RoleArn.Set(&v)
}
// SetRoleArnNil sets the value for RoleArn to be an explicit nil
func (o *UpdateAwsSourceAccountAttributes) SetRoleArnNil() {
	o.RoleArn.Set(nil)
}

// UnsetRoleArn ensures that no value is present for RoleArn, not even an explicit nil
func (o *UpdateAwsSourceAccountAttributes) UnsetRoleArn() {
	o.RoleArn.Unset()
}

func (o UpdateAwsSourceAccountAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateAwsSourceAccountAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.RoleArn.IsSet() {
		toSerialize["roleArn"] = o.RoleArn.Get()
	}
	return toSerialize, nil
}

type NullableUpdateAwsSourceAccountAttributes struct {
	value *UpdateAwsSourceAccountAttributes
	isSet bool
}

func (v NullableUpdateAwsSourceAccountAttributes) Get() *UpdateAwsSourceAccountAttributes {
	return v.value
}

func (v *NullableUpdateAwsSourceAccountAttributes) Set(val *UpdateAwsSourceAccountAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateAwsSourceAccountAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateAwsSourceAccountAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateAwsSourceAccountAttributes(val *UpdateAwsSourceAccountAttributes) *NullableUpdateAwsSourceAccountAttributes {
	return &NullableUpdateAwsSourceAccountAttributes{value: val, isSet: true}
}

func (v NullableUpdateAwsSourceAccountAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateAwsSourceAccountAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


