/*
Eon API

The Eon.io REST API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eon

import (
	"encoding/json"
)

// checks if the FindingExclusionResourceFilter type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FindingExclusionResourceFilter{}

// FindingExclusionResourceFilter Filters by the resource a resource-scoped exclusion applies to. Account-wide exclusions never match it.
type FindingExclusionResourceFilter struct {
	// Matches exclusions for any of these resources, by cloud provider resource ID. An empty list applies no filter; IDs that match no resource in the account match no exclusion. 
	In []string `json:"in,omitempty"`
}

// NewFindingExclusionResourceFilter instantiates a new FindingExclusionResourceFilter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFindingExclusionResourceFilter() *FindingExclusionResourceFilter {
	this := FindingExclusionResourceFilter{}
	return &this
}

// NewFindingExclusionResourceFilterWithDefaults instantiates a new FindingExclusionResourceFilter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFindingExclusionResourceFilterWithDefaults() *FindingExclusionResourceFilter {
	this := FindingExclusionResourceFilter{}
	return &this
}

// GetIn returns the In field value if set, zero value otherwise.
func (o *FindingExclusionResourceFilter) GetIn() []string {
	if o == nil || IsNil(o.In) {
		var ret []string
		return ret
	}
	return o.In
}

// GetInOk returns a tuple with the In field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindingExclusionResourceFilter) GetInOk() ([]string, bool) {
	if o == nil || IsNil(o.In) {
		return nil, false
	}
	return o.In, true
}

// HasIn returns a boolean if a field has been set.
func (o *FindingExclusionResourceFilter) HasIn() bool {
	if o != nil && !IsNil(o.In) {
		return true
	}

	return false
}

// SetIn gets a reference to the given []string and assigns it to the In field.
func (o *FindingExclusionResourceFilter) SetIn(v []string) {
	o.In = v
}

func (o FindingExclusionResourceFilter) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FindingExclusionResourceFilter) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.In) {
		toSerialize["in"] = o.In
	}
	return toSerialize, nil
}

type NullableFindingExclusionResourceFilter struct {
	value *FindingExclusionResourceFilter
	isSet bool
}

func (v NullableFindingExclusionResourceFilter) Get() *FindingExclusionResourceFilter {
	return v.value
}

func (v *NullableFindingExclusionResourceFilter) Set(val *FindingExclusionResourceFilter) {
	v.value = val
	v.isSet = true
}

func (v NullableFindingExclusionResourceFilter) IsSet() bool {
	return v.isSet
}

func (v *NullableFindingExclusionResourceFilter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFindingExclusionResourceFilter(val *FindingExclusionResourceFilter) *NullableFindingExclusionResourceFilter {
	return &NullableFindingExclusionResourceFilter{value: val, isSet: true}
}

func (v NullableFindingExclusionResourceFilter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFindingExclusionResourceFilter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


