/*
Eon API

The Eon.io REST API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eon

import (
	"encoding/json"
)

// checks if the AwsAccountMetricsDestination type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AwsAccountMetricsDestination{}

// AwsAccountMetricsDestination struct for AwsAccountMetricsDestination
type AwsAccountMetricsDestination struct {
	// CloudWatch region to publish metrics to.
	Region *string `json:"region,omitempty"`
}

// NewAwsAccountMetricsDestination instantiates a new AwsAccountMetricsDestination object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAwsAccountMetricsDestination() *AwsAccountMetricsDestination {
	this := AwsAccountMetricsDestination{}
	return &this
}

// NewAwsAccountMetricsDestinationWithDefaults instantiates a new AwsAccountMetricsDestination object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAwsAccountMetricsDestinationWithDefaults() *AwsAccountMetricsDestination {
	this := AwsAccountMetricsDestination{}
	return &this
}

// GetRegion returns the Region field value if set, zero value otherwise.
func (o *AwsAccountMetricsDestination) GetRegion() string {
	if o == nil || IsNil(o.Region) {
		var ret string
		return ret
	}
	return *o.Region
}

// GetRegionOk returns a tuple with the Region field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AwsAccountMetricsDestination) GetRegionOk() (*string, bool) {
	if o == nil || IsNil(o.Region) {
		return nil, false
	}
	return o.Region, true
}

// HasRegion returns a boolean if a field has been set.
func (o *AwsAccountMetricsDestination) HasRegion() bool {
	if o != nil && !IsNil(o.Region) {
		return true
	}

	return false
}

// SetRegion gets a reference to the given string and assigns it to the Region field.
func (o *AwsAccountMetricsDestination) SetRegion(v string) {
	o.Region = &v
}

func (o AwsAccountMetricsDestination) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AwsAccountMetricsDestination) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Region) {
		toSerialize["region"] = o.Region
	}
	return toSerialize, nil
}

type NullableAwsAccountMetricsDestination struct {
	value *AwsAccountMetricsDestination
	isSet bool
}

func (v NullableAwsAccountMetricsDestination) Get() *AwsAccountMetricsDestination {
	return v.value
}

func (v *NullableAwsAccountMetricsDestination) Set(val *AwsAccountMetricsDestination) {
	v.value = val
	v.isSet = true
}

func (v NullableAwsAccountMetricsDestination) IsSet() bool {
	return v.isSet
}

func (v *NullableAwsAccountMetricsDestination) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAwsAccountMetricsDestination(val *AwsAccountMetricsDestination) *NullableAwsAccountMetricsDestination {
	return &NullableAwsAccountMetricsDestination{value: val, isSet: true}
}

func (v NullableAwsAccountMetricsDestination) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAwsAccountMetricsDestination) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


