/*
Eon API

The Eon.io REST API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eon

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateActionApprovalRuleResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateActionApprovalRuleResponse{}

// CreateActionApprovalRuleResponse Response containing the newly created action approval rule.
type CreateActionApprovalRuleResponse struct {
	ActionApprovalRule NullableActionApprovalRule `json:"actionApprovalRule"`
}

type _CreateActionApprovalRuleResponse CreateActionApprovalRuleResponse

// NewCreateActionApprovalRuleResponse instantiates a new CreateActionApprovalRuleResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateActionApprovalRuleResponse(actionApprovalRule NullableActionApprovalRule) *CreateActionApprovalRuleResponse {
	this := CreateActionApprovalRuleResponse{}
	this.ActionApprovalRule = actionApprovalRule
	return &this
}

// NewCreateActionApprovalRuleResponseWithDefaults instantiates a new CreateActionApprovalRuleResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateActionApprovalRuleResponseWithDefaults() *CreateActionApprovalRuleResponse {
	this := CreateActionApprovalRuleResponse{}
	return &this
}

// GetActionApprovalRule returns the ActionApprovalRule field value
// If the value is explicit nil, the zero value for ActionApprovalRule will be returned
func (o *CreateActionApprovalRuleResponse) GetActionApprovalRule() ActionApprovalRule {
	if o == nil || o.ActionApprovalRule.Get() == nil {
		var ret ActionApprovalRule
		return ret
	}

	return *o.ActionApprovalRule.Get()
}

// GetActionApprovalRuleOk returns a tuple with the ActionApprovalRule field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateActionApprovalRuleResponse) GetActionApprovalRuleOk() (*ActionApprovalRule, bool) {
	if o == nil {
		return nil, false
	}
	return o.ActionApprovalRule.Get(), o.ActionApprovalRule.IsSet()
}

// SetActionApprovalRule sets field value
func (o *CreateActionApprovalRuleResponse) SetActionApprovalRule(v ActionApprovalRule) {
	o.ActionApprovalRule.Set(&v)
}

func (o CreateActionApprovalRuleResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateActionApprovalRuleResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["actionApprovalRule"] = o.ActionApprovalRule.Get()
	return toSerialize, nil
}

func (o *CreateActionApprovalRuleResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"actionApprovalRule",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateActionApprovalRuleResponse := _CreateActionApprovalRuleResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateActionApprovalRuleResponse)

	if err != nil {
		return err
	}

	*o = CreateActionApprovalRuleResponse(varCreateActionApprovalRuleResponse)

	return err
}

type NullableCreateActionApprovalRuleResponse struct {
	value *CreateActionApprovalRuleResponse
	isSet bool
}

func (v NullableCreateActionApprovalRuleResponse) Get() *CreateActionApprovalRuleResponse {
	return v.value
}

func (v *NullableCreateActionApprovalRuleResponse) Set(val *CreateActionApprovalRuleResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateActionApprovalRuleResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateActionApprovalRuleResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateActionApprovalRuleResponse(val *CreateActionApprovalRuleResponse) *NullableCreateActionApprovalRuleResponse {
	return &NullableCreateActionApprovalRuleResponse{value: val, isSet: true}
}

func (v NullableCreateActionApprovalRuleResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateActionApprovalRuleResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


