/*
Eon API

The Eon.io REST API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eon

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SourceAccountAttributesInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SourceAccountAttributesInput{}

// SourceAccountAttributesInput struct for SourceAccountAttributesInput
type SourceAccountAttributesInput struct {
	CloudProvider Provider                                `json:"cloudProvider"`
	Aws           NullableAwsSourceAccountAttributesInput   `json:"aws,omitempty"`
	Azure         NullableAzureSourceAccountAttributesInput `json:"azure,omitempty"`
	Gcp           NullableGcpSourceAccountAttributesInput   `json:"gcp,omitempty"`
}

type _SourceAccountAttributesInput SourceAccountAttributesInput

// NewSourceAccountAttributesInput instantiates a new SourceAccountAttributesInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSourceAccountAttributesInput(cloudProvider Provider) *SourceAccountAttributesInput {
	this := SourceAccountAttributesInput{}
	this.CloudProvider = cloudProvider
	return &this
}

// NewSourceAccountAttributesInputWithDefaults instantiates a new SourceAccountAttributesInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSourceAccountAttributesInputWithDefaults() *SourceAccountAttributesInput {
	this := SourceAccountAttributesInput{}
	return &this
}

// GetCloudProvider returns the CloudProvider field value
func (o *SourceAccountAttributesInput) GetCloudProvider() Provider {
	if o == nil {
		var ret Provider
		return ret
	}

	return o.CloudProvider
}

// GetCloudProviderOk returns a tuple with the CloudProvider field value
// and a boolean to check if the value has been set.
func (o *SourceAccountAttributesInput) GetCloudProviderOk() (*Provider, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CloudProvider, true
}

// SetCloudProvider sets field value
func (o *SourceAccountAttributesInput) SetCloudProvider(v Provider) {
	o.CloudProvider = v
}

// GetAws returns the Aws field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SourceAccountAttributesInput) GetAws() AwsSourceAccountAttributesInput {
	if o == nil || IsNil(o.Aws.Get()) {
		var ret AwsSourceAccountAttributesInput
		return ret
	}
	return *o.Aws.Get()
}

// GetAwsOk returns a tuple with the Aws field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SourceAccountAttributesInput) GetAwsOk() (*AwsSourceAccountAttributesInput, bool) {
	if o == nil {
		return nil, false
	}
	return o.Aws.Get(), o.Aws.IsSet()
}

// HasAws returns a boolean if a field has been set.
func (o *SourceAccountAttributesInput) HasAws() bool {
	if o != nil && o.Aws.IsSet() {
		return true
	}

	return false
}

// SetAws gets a reference to the given NullableAwsSourceAccountAttributesInput and assigns it to the Aws field.
func (o *SourceAccountAttributesInput) SetAws(v AwsSourceAccountAttributesInput) {
	o.Aws.Set(&v)
}
// SetAwsNil sets the value for Aws to be an explicit nil
func (o *SourceAccountAttributesInput) SetAwsNil() {
	o.Aws.Set(nil)
}

// UnsetAws ensures that no value is present for Aws, not even an explicit nil
func (o *SourceAccountAttributesInput) UnsetAws() {
	o.Aws.Unset()
}

// GetAzure returns the Azure field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SourceAccountAttributesInput) GetAzure() AzureSourceAccountAttributesInput {
	if o == nil || IsNil(o.Azure.Get()) {
		var ret AzureSourceAccountAttributesInput
		return ret
	}
	return *o.Azure.Get()
}

// GetAzureOk returns a tuple with the Azure field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SourceAccountAttributesInput) GetAzureOk() (*AzureSourceAccountAttributesInput, bool) {
	if o == nil {
		return nil, false
	}
	return o.Azure.Get(), o.Azure.IsSet()
}

// HasAzure returns a boolean if a field has been set.
func (o *SourceAccountAttributesInput) HasAzure() bool {
	if o != nil && o.Azure.IsSet() {
		return true
	}

	return false
}

// SetAzure gets a reference to the given NullableAzureSourceAccountAttributesInput and assigns it to the Azure field.
func (o *SourceAccountAttributesInput) SetAzure(v AzureSourceAccountAttributesInput) {
	o.Azure.Set(&v)
}

// SetAzureNil sets the value for Azure to be an explicit nil
func (o *SourceAccountAttributesInput) SetAzureNil() {
	o.Azure.Set(nil)
}

// UnsetAzure ensures that no value is present for Azure, not even an explicit nil
func (o *SourceAccountAttributesInput) UnsetAzure() {
	o.Azure.Unset()
}

// GetGcp returns the Gcp field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *SourceAccountAttributesInput) GetGcp() GcpSourceAccountAttributesInput {
	if o == nil || IsNil(o.Gcp.Get()) {
		var ret GcpSourceAccountAttributesInput
		return ret
	}
	return *o.Gcp.Get()
}

// GetGcpOk returns a tuple with the Gcp field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *SourceAccountAttributesInput) GetGcpOk() (*GcpSourceAccountAttributesInput, bool) {
	if o == nil {
		return nil, false
	}
	return o.Gcp.Get(), o.Gcp.IsSet()
}

// HasGcp returns a boolean if a field has been set.
func (o *SourceAccountAttributesInput) HasGcp() bool {
	if o != nil && o.Gcp.IsSet() {
		return true
	}

	return false
}

// SetGcp gets a reference to the given NullableGcpSourceAccountAttributesInput and assigns it to the Gcp field.
func (o *SourceAccountAttributesInput) SetGcp(v GcpSourceAccountAttributesInput) {
	o.Gcp.Set(&v)
}

// SetGcpNil sets the value for Gcp to be an explicit nil
func (o *SourceAccountAttributesInput) SetGcpNil() {
	o.Gcp.Set(nil)
}

// UnsetGcp ensures that no value is present for Gcp, not even an explicit nil
func (o *SourceAccountAttributesInput) UnsetGcp() {
	o.Gcp.Unset()
}

func (o SourceAccountAttributesInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SourceAccountAttributesInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cloudProvider"] = o.CloudProvider
	if o.Aws.IsSet() {
		toSerialize["aws"] = o.Aws.Get()
	}
	if o.Azure.IsSet() {
		toSerialize["azure"] = o.Azure.Get()
	}
	if o.Gcp.IsSet() {
		toSerialize["gcp"] = o.Gcp.Get()
	}
	return toSerialize, nil
}

func (o *SourceAccountAttributesInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"cloudProvider",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSourceAccountAttributesInput := _SourceAccountAttributesInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSourceAccountAttributesInput)

	if err != nil {
		return err
	}

	*o = SourceAccountAttributesInput(varSourceAccountAttributesInput)

	return err
}

type NullableSourceAccountAttributesInput struct {
	value *SourceAccountAttributesInput
	isSet bool
}

func (v NullableSourceAccountAttributesInput) Get() *SourceAccountAttributesInput {
	return v.value
}

func (v *NullableSourceAccountAttributesInput) Set(val *SourceAccountAttributesInput) {
	v.value = val
	v.isSet = true
}

func (v NullableSourceAccountAttributesInput) IsSet() bool {
	return v.isSet
}

func (v *NullableSourceAccountAttributesInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSourceAccountAttributesInput(val *SourceAccountAttributesInput) *NullableSourceAccountAttributesInput {
	return &NullableSourceAccountAttributesInput{value: val, isSet: true}
}

func (v NullableSourceAccountAttributesInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSourceAccountAttributesInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


