/*
Eon API

The Eon.io REST API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eon

import (
	"encoding/json"
	"fmt"
)

// ConfigurationStatus Whether a backup is configured for this resource, and if not why not. One of the independent axes of resource status, alongside `complianceStatus` — neither outranks the other, and a pending customer action is reported as a blocker rather than as a status here. In scope, and counted: `INITIAL_CLASSIFICATION` — found, type still being worked out. `ACCESS_LOST` — Eon can no longer reach the resource; permissions were removed or changed, and nobody decided this. `CLASSIFICATION_FAILED` — Eon tried repeatedly to classify it and gave up. The type is supported; something about this instance defeated it. `UNASSIGNED` — classified and eligible, but no backup policy covers it. `ASSIGNED` — a backup policy covers it, storage-gateway policies included: this axis answers whether a backup is configured, not who takes it. Out of scope, and not counted — four causes with one shared consequence, kept distinct because a customer can do different things about each: `TERMINATED` — deleted in the cloud. `DISCONNECTED` — the customer told Eon not to discover it, by deactivating the account or by a discovery exclusion rule. `EXCLUDED_FROM_BACKUP` — the customer chose not to back it up. `UNSUPPORTED` — Eon cannot back up this kind of resource. 
type ConfigurationStatus string

// List of ConfigurationStatus
const (
	CONFIGURATION_STATUS_INITIAL_CLASSIFICATION ConfigurationStatus = "INITIAL_CLASSIFICATION"
	CONFIGURATION_STATUS_ACCESS_LOST ConfigurationStatus = "ACCESS_LOST"
	CONFIGURATION_STATUS_CLASSIFICATION_FAILED ConfigurationStatus = "CLASSIFICATION_FAILED"
	CONFIGURATION_STATUS_UNASSIGNED ConfigurationStatus = "UNASSIGNED"
	CONFIGURATION_STATUS_ASSIGNED ConfigurationStatus = "ASSIGNED"
	CONFIGURATION_STATUS_TERMINATED ConfigurationStatus = "TERMINATED"
	CONFIGURATION_STATUS_DISCONNECTED ConfigurationStatus = "DISCONNECTED"
	CONFIGURATION_STATUS_EXCLUDED_FROM_BACKUP ConfigurationStatus = "EXCLUDED_FROM_BACKUP"
	CONFIGURATION_STATUS_LIMIT_EXCEEDED ConfigurationStatus = "LIMIT_EXCEEDED"
	CONFIGURATION_STATUS_UNSUPPORTED ConfigurationStatus = "UNSUPPORTED"
)

// All allowed values of ConfigurationStatus enum
var AllowedConfigurationStatusEnumValues = []ConfigurationStatus{
	"INITIAL_CLASSIFICATION",
	"ACCESS_LOST",
	"CLASSIFICATION_FAILED",
	"UNASSIGNED",
	"ASSIGNED",
	"TERMINATED",
	"DISCONNECTED",
	"EXCLUDED_FROM_BACKUP",
	"LIMIT_EXCEEDED",
	"UNSUPPORTED",
}

func (v *ConfigurationStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	// x-extensible-enum (EON-15210): open set. Accept unknown values instead of failing so a
	// value added to the server's enum does not break decoding for an already-released client.
	*v = ConfigurationStatus(value)
	return nil
}

// NewConfigurationStatusFromValue returns a pointer to a valid ConfigurationStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewConfigurationStatusFromValue(v string) (*ConfigurationStatus, error) {
	ev := ConfigurationStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for ConfigurationStatus: valid values are %v", v, AllowedConfigurationStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v ConfigurationStatus) IsValid() bool {
	for _, existing := range AllowedConfigurationStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to ConfigurationStatus value
func (v ConfigurationStatus) Ptr() *ConfigurationStatus {
	return &v
}

type NullableConfigurationStatus struct {
	value *ConfigurationStatus
	isSet bool
}

func (v NullableConfigurationStatus) Get() *ConfigurationStatus {
	return v.value
}

func (v *NullableConfigurationStatus) Set(val *ConfigurationStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableConfigurationStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableConfigurationStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConfigurationStatus(val *ConfigurationStatus) *NullableConfigurationStatus {
	return &NullableConfigurationStatus{value: val, isSet: true}
}

func (v NullableConfigurationStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConfigurationStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

