/*
Eon API

The Eon.io REST API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eon

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ConnectSourceAwsOrganizationalUnitResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConnectSourceAwsOrganizationalUnitResponse{}

// ConnectSourceAwsOrganizationalUnitResponse struct for ConnectSourceAwsOrganizationalUnitResponse
type ConnectSourceAwsOrganizationalUnitResponse struct {
	OrganizationalUnit SourceAwsOrganizationalUnit `json:"organizationalUnit"`
}

type _ConnectSourceAwsOrganizationalUnitResponse ConnectSourceAwsOrganizationalUnitResponse

// NewConnectSourceAwsOrganizationalUnitResponse instantiates a new ConnectSourceAwsOrganizationalUnitResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConnectSourceAwsOrganizationalUnitResponse(organizationalUnit SourceAwsOrganizationalUnit) *ConnectSourceAwsOrganizationalUnitResponse {
	this := ConnectSourceAwsOrganizationalUnitResponse{}
	this.OrganizationalUnit = organizationalUnit
	return &this
}

// NewConnectSourceAwsOrganizationalUnitResponseWithDefaults instantiates a new ConnectSourceAwsOrganizationalUnitResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConnectSourceAwsOrganizationalUnitResponseWithDefaults() *ConnectSourceAwsOrganizationalUnitResponse {
	this := ConnectSourceAwsOrganizationalUnitResponse{}
	return &this
}

// GetOrganizationalUnit returns the OrganizationalUnit field value
func (o *ConnectSourceAwsOrganizationalUnitResponse) GetOrganizationalUnit() SourceAwsOrganizationalUnit {
	if o == nil {
		var ret SourceAwsOrganizationalUnit
		return ret
	}

	return o.OrganizationalUnit
}

// GetOrganizationalUnitOk returns a tuple with the OrganizationalUnit field value
// and a boolean to check if the value has been set.
func (o *ConnectSourceAwsOrganizationalUnitResponse) GetOrganizationalUnitOk() (*SourceAwsOrganizationalUnit, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrganizationalUnit, true
}

// SetOrganizationalUnit sets field value
func (o *ConnectSourceAwsOrganizationalUnitResponse) SetOrganizationalUnit(v SourceAwsOrganizationalUnit) {
	o.OrganizationalUnit = v
}

func (o ConnectSourceAwsOrganizationalUnitResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConnectSourceAwsOrganizationalUnitResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["organizationalUnit"] = o.OrganizationalUnit
	return toSerialize, nil
}

func (o *ConnectSourceAwsOrganizationalUnitResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"organizationalUnit",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConnectSourceAwsOrganizationalUnitResponse := _ConnectSourceAwsOrganizationalUnitResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConnectSourceAwsOrganizationalUnitResponse)

	if err != nil {
		return err
	}

	*o = ConnectSourceAwsOrganizationalUnitResponse(varConnectSourceAwsOrganizationalUnitResponse)

	return err
}

type NullableConnectSourceAwsOrganizationalUnitResponse struct {
	value *ConnectSourceAwsOrganizationalUnitResponse
	isSet bool
}

func (v NullableConnectSourceAwsOrganizationalUnitResponse) Get() *ConnectSourceAwsOrganizationalUnitResponse {
	return v.value
}

func (v *NullableConnectSourceAwsOrganizationalUnitResponse) Set(val *ConnectSourceAwsOrganizationalUnitResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableConnectSourceAwsOrganizationalUnitResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableConnectSourceAwsOrganizationalUnitResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConnectSourceAwsOrganizationalUnitResponse(val *ConnectSourceAwsOrganizationalUnitResponse) *NullableConnectSourceAwsOrganizationalUnitResponse {
	return &NullableConnectSourceAwsOrganizationalUnitResponse{value: val, isSet: true}
}

func (v NullableConnectSourceAwsOrganizationalUnitResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConnectSourceAwsOrganizationalUnitResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


