/*
Eon API

The Eon.io REST API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eon

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SameSourceAccountRestoreLimits type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SameSourceAccountRestoreLimits{}

// SameSourceAccountRestoreLimits Restricts restores so a resource may only be restored back to its original source cloud account, matched on the cloud-provider account ID (not the Eon account ID). When `dataAccessRuleId` is set the restriction applies only to resources matching that access condition; otherwise it applies to all resources granted by the role. 
type SameSourceAccountRestoreLimits struct {
	// Whether the same-source-account restore restriction is active.
	Enabled bool `json:"enabled"`
	// Optional. The id of an access condition (an entry in `accessConditions`) that scopes which resources the restriction applies to. Omit to apply the restriction to all resources. 
	DataAccessRuleId *string `json:"dataAccessRuleId,omitempty"`
}

type _SameSourceAccountRestoreLimits SameSourceAccountRestoreLimits

// NewSameSourceAccountRestoreLimits instantiates a new SameSourceAccountRestoreLimits object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSameSourceAccountRestoreLimits(enabled bool) *SameSourceAccountRestoreLimits {
	this := SameSourceAccountRestoreLimits{}
	this.Enabled = enabled
	return &this
}

// NewSameSourceAccountRestoreLimitsWithDefaults instantiates a new SameSourceAccountRestoreLimits object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSameSourceAccountRestoreLimitsWithDefaults() *SameSourceAccountRestoreLimits {
	this := SameSourceAccountRestoreLimits{}
	return &this
}

// GetEnabled returns the Enabled field value
func (o *SameSourceAccountRestoreLimits) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *SameSourceAccountRestoreLimits) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *SameSourceAccountRestoreLimits) SetEnabled(v bool) {
	o.Enabled = v
}

// GetDataAccessRuleId returns the DataAccessRuleId field value if set, zero value otherwise.
func (o *SameSourceAccountRestoreLimits) GetDataAccessRuleId() string {
	if o == nil || IsNil(o.DataAccessRuleId) {
		var ret string
		return ret
	}
	return *o.DataAccessRuleId
}

// GetDataAccessRuleIdOk returns a tuple with the DataAccessRuleId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SameSourceAccountRestoreLimits) GetDataAccessRuleIdOk() (*string, bool) {
	if o == nil || IsNil(o.DataAccessRuleId) {
		return nil, false
	}
	return o.DataAccessRuleId, true
}

// HasDataAccessRuleId returns a boolean if a field has been set.
func (o *SameSourceAccountRestoreLimits) HasDataAccessRuleId() bool {
	if o != nil && !IsNil(o.DataAccessRuleId) {
		return true
	}

	return false
}

// SetDataAccessRuleId gets a reference to the given string and assigns it to the DataAccessRuleId field.
func (o *SameSourceAccountRestoreLimits) SetDataAccessRuleId(v string) {
	o.DataAccessRuleId = &v
}

func (o SameSourceAccountRestoreLimits) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SameSourceAccountRestoreLimits) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["enabled"] = o.Enabled
	if !IsNil(o.DataAccessRuleId) {
		toSerialize["dataAccessRuleId"] = o.DataAccessRuleId
	}
	return toSerialize, nil
}

func (o *SameSourceAccountRestoreLimits) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"enabled",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSameSourceAccountRestoreLimits := _SameSourceAccountRestoreLimits{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSameSourceAccountRestoreLimits)

	if err != nil {
		return err
	}

	*o = SameSourceAccountRestoreLimits(varSameSourceAccountRestoreLimits)

	return err
}

type NullableSameSourceAccountRestoreLimits struct {
	value *SameSourceAccountRestoreLimits
	isSet bool
}

func (v NullableSameSourceAccountRestoreLimits) Get() *SameSourceAccountRestoreLimits {
	return v.value
}

func (v *NullableSameSourceAccountRestoreLimits) Set(val *SameSourceAccountRestoreLimits) {
	v.value = val
	v.isSet = true
}

func (v NullableSameSourceAccountRestoreLimits) IsSet() bool {
	return v.isSet
}

func (v *NullableSameSourceAccountRestoreLimits) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSameSourceAccountRestoreLimits(val *SameSourceAccountRestoreLimits) *NullableSameSourceAccountRestoreLimits {
	return &NullableSameSourceAccountRestoreLimits{value: val, isSet: true}
}

func (v NullableSameSourceAccountRestoreLimits) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSameSourceAccountRestoreLimits) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


