/*
Eon API

The Eon.io REST API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eon

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateVaultRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateVaultRequest{}

// CreateVaultRequest struct for CreateVaultRequest
type CreateVaultRequest struct {
	// Vault display name.
	Name string `json:"name"`
	// Region where the vault is hosted.
	Region string `json:"region"`
	VaultAttributes VaultProviderAttributesInput `json:"vaultAttributes"`
}

type _CreateVaultRequest CreateVaultRequest

// NewCreateVaultRequest instantiates a new CreateVaultRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateVaultRequest(name string, region string, vaultAttributes VaultProviderAttributesInput) *CreateVaultRequest {
	this := CreateVaultRequest{}
	this.Name = name
	this.Region = region
	this.VaultAttributes = vaultAttributes
	return &this
}

// NewCreateVaultRequestWithDefaults instantiates a new CreateVaultRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateVaultRequestWithDefaults() *CreateVaultRequest {
	this := CreateVaultRequest{}
	return &this
}

// GetName returns the Name field value
func (o *CreateVaultRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateVaultRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateVaultRequest) SetName(v string) {
	o.Name = v
}

// GetRegion returns the Region field value
func (o *CreateVaultRequest) GetRegion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Region
}

// GetRegionOk returns a tuple with the Region field value
// and a boolean to check if the value has been set.
func (o *CreateVaultRequest) GetRegionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Region, true
}

// SetRegion sets field value
func (o *CreateVaultRequest) SetRegion(v string) {
	o.Region = v
}

// GetVaultAttributes returns the VaultAttributes field value
func (o *CreateVaultRequest) GetVaultAttributes() VaultProviderAttributesInput {
	if o == nil {
		var ret VaultProviderAttributesInput
		return ret
	}

	return o.VaultAttributes
}

// GetVaultAttributesOk returns a tuple with the VaultAttributes field value
// and a boolean to check if the value has been set.
func (o *CreateVaultRequest) GetVaultAttributesOk() (*VaultProviderAttributesInput, bool) {
	if o == nil {
		return nil, false
	}
	return &o.VaultAttributes, true
}

// SetVaultAttributes sets field value
func (o *CreateVaultRequest) SetVaultAttributes(v VaultProviderAttributesInput) {
	o.VaultAttributes = v
}

func (o CreateVaultRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateVaultRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["region"] = o.Region
	toSerialize["vaultAttributes"] = o.VaultAttributes
	return toSerialize, nil
}

func (o *CreateVaultRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"region",
		"vaultAttributes",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateVaultRequest := _CreateVaultRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateVaultRequest)

	if err != nil {
		return err
	}

	*o = CreateVaultRequest(varCreateVaultRequest)

	return err
}

type NullableCreateVaultRequest struct {
	value *CreateVaultRequest
	isSet bool
}

func (v NullableCreateVaultRequest) Get() *CreateVaultRequest {
	return v.value
}

func (v *NullableCreateVaultRequest) Set(val *CreateVaultRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateVaultRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateVaultRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateVaultRequest(val *CreateVaultRequest) *NullableCreateVaultRequest {
	return &NullableCreateVaultRequest{value: val, isSet: true}
}

func (v NullableCreateVaultRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateVaultRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


