/*
Eon API

The Eon.io REST API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eon

import (
	"encoding/json"
)

// checks if the UpdateSourceAccountRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateSourceAccountRequest{}

// UpdateSourceAccountRequest struct for UpdateSourceAccountRequest
type UpdateSourceAccountRequest struct {
	// Display name for the source account in Eon.
	Name NullableString `json:"name,omitempty"`
	SourceAccountAttributes *UpdateSourceAccountAttributesInput `json:"sourceAccountAttributes,omitempty"`
}

// NewUpdateSourceAccountRequest instantiates a new UpdateSourceAccountRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateSourceAccountRequest() *UpdateSourceAccountRequest {
	this := UpdateSourceAccountRequest{}
	return &this
}

// NewUpdateSourceAccountRequestWithDefaults instantiates a new UpdateSourceAccountRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateSourceAccountRequestWithDefaults() *UpdateSourceAccountRequest {
	this := UpdateSourceAccountRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateSourceAccountRequest) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateSourceAccountRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *UpdateSourceAccountRequest) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *UpdateSourceAccountRequest) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *UpdateSourceAccountRequest) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *UpdateSourceAccountRequest) UnsetName() {
	o.Name.Unset()
}

// GetSourceAccountAttributes returns the SourceAccountAttributes field value if set, zero value otherwise.
func (o *UpdateSourceAccountRequest) GetSourceAccountAttributes() UpdateSourceAccountAttributesInput {
	if o == nil || IsNil(o.SourceAccountAttributes) {
		var ret UpdateSourceAccountAttributesInput
		return ret
	}
	return *o.SourceAccountAttributes
}

// GetSourceAccountAttributesOk returns a tuple with the SourceAccountAttributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateSourceAccountRequest) GetSourceAccountAttributesOk() (*UpdateSourceAccountAttributesInput, bool) {
	if o == nil || IsNil(o.SourceAccountAttributes) {
		return nil, false
	}
	return o.SourceAccountAttributes, true
}

// HasSourceAccountAttributes returns a boolean if a field has been set.
func (o *UpdateSourceAccountRequest) HasSourceAccountAttributes() bool {
	if o != nil && !IsNil(o.SourceAccountAttributes) {
		return true
	}

	return false
}

// SetSourceAccountAttributes gets a reference to the given UpdateSourceAccountAttributesInput and assigns it to the SourceAccountAttributes field.
func (o *UpdateSourceAccountRequest) SetSourceAccountAttributes(v UpdateSourceAccountAttributesInput) {
	o.SourceAccountAttributes = &v
}

func (o UpdateSourceAccountRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateSourceAccountRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if !IsNil(o.SourceAccountAttributes) {
		toSerialize["sourceAccountAttributes"] = o.SourceAccountAttributes
	}
	return toSerialize, nil
}

type NullableUpdateSourceAccountRequest struct {
	value *UpdateSourceAccountRequest
	isSet bool
}

func (v NullableUpdateSourceAccountRequest) Get() *UpdateSourceAccountRequest {
	return v.value
}

func (v *NullableUpdateSourceAccountRequest) Set(val *UpdateSourceAccountRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateSourceAccountRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateSourceAccountRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateSourceAccountRequest(val *UpdateSourceAccountRequest) *NullableUpdateSourceAccountRequest {
	return &NullableUpdateSourceAccountRequest{value: val, isSet: true}
}

func (v NullableUpdateSourceAccountRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateSourceAccountRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


