/*
Eon API

The Eon.io REST API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eon

import (
	"encoding/json"
)

// checks if the CostDataRecordDimensions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CostDataRecordDimensions{}

// CostDataRecordDimensions Grouping dimensions (e.g. cloudProvider, meteringDimension, etc.)
type CostDataRecordDimensions struct {
	CloudProvider *Provider `json:"cloudProvider,omitempty"`
	ResourceType *ResourceType `json:"resourceType,omitempty"`
	// Eon-assigned resource ID
	ResourceId *string `json:"resourceId,omitempty"`
	// Source account provider id
	SourceAccountProviderId *string `json:"sourceAccountProviderId,omitempty"`
}

// NewCostDataRecordDimensions instantiates a new CostDataRecordDimensions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCostDataRecordDimensions() *CostDataRecordDimensions {
	this := CostDataRecordDimensions{}
	return &this
}

// NewCostDataRecordDimensionsWithDefaults instantiates a new CostDataRecordDimensions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCostDataRecordDimensionsWithDefaults() *CostDataRecordDimensions {
	this := CostDataRecordDimensions{}
	return &this
}

// GetCloudProvider returns the CloudProvider field value if set, zero value otherwise.
func (o *CostDataRecordDimensions) GetCloudProvider() Provider {
	if o == nil || IsNil(o.CloudProvider) {
		var ret Provider
		return ret
	}
	return *o.CloudProvider
}

// GetCloudProviderOk returns a tuple with the CloudProvider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CostDataRecordDimensions) GetCloudProviderOk() (*Provider, bool) {
	if o == nil || IsNil(o.CloudProvider) {
		return nil, false
	}
	return o.CloudProvider, true
}

// HasCloudProvider returns a boolean if a field has been set.
func (o *CostDataRecordDimensions) HasCloudProvider() bool {
	if o != nil && !IsNil(o.CloudProvider) {
		return true
	}

	return false
}

// SetCloudProvider gets a reference to the given Provider and assigns it to the CloudProvider field.
func (o *CostDataRecordDimensions) SetCloudProvider(v Provider) {
	o.CloudProvider = &v
}

// GetResourceType returns the ResourceType field value if set, zero value otherwise.
func (o *CostDataRecordDimensions) GetResourceType() ResourceType {
	if o == nil || IsNil(o.ResourceType) {
		var ret ResourceType
		return ret
	}
	return *o.ResourceType
}

// GetResourceTypeOk returns a tuple with the ResourceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CostDataRecordDimensions) GetResourceTypeOk() (*ResourceType, bool) {
	if o == nil || IsNil(o.ResourceType) {
		return nil, false
	}
	return o.ResourceType, true
}

// HasResourceType returns a boolean if a field has been set.
func (o *CostDataRecordDimensions) HasResourceType() bool {
	if o != nil && !IsNil(o.ResourceType) {
		return true
	}

	return false
}

// SetResourceType gets a reference to the given ResourceType and assigns it to the ResourceType field.
func (o *CostDataRecordDimensions) SetResourceType(v ResourceType) {
	o.ResourceType = &v
}

// GetResourceId returns the ResourceId field value if set, zero value otherwise.
func (o *CostDataRecordDimensions) GetResourceId() string {
	if o == nil || IsNil(o.ResourceId) {
		var ret string
		return ret
	}
	return *o.ResourceId
}

// GetResourceIdOk returns a tuple with the ResourceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CostDataRecordDimensions) GetResourceIdOk() (*string, bool) {
	if o == nil || IsNil(o.ResourceId) {
		return nil, false
	}
	return o.ResourceId, true
}

// HasResourceId returns a boolean if a field has been set.
func (o *CostDataRecordDimensions) HasResourceId() bool {
	if o != nil && !IsNil(o.ResourceId) {
		return true
	}

	return false
}

// SetResourceId gets a reference to the given string and assigns it to the ResourceId field.
func (o *CostDataRecordDimensions) SetResourceId(v string) {
	o.ResourceId = &v
}

// GetSourceAccountProviderId returns the SourceAccountProviderId field value if set, zero value otherwise.
func (o *CostDataRecordDimensions) GetSourceAccountProviderId() string {
	if o == nil || IsNil(o.SourceAccountProviderId) {
		var ret string
		return ret
	}
	return *o.SourceAccountProviderId
}

// GetSourceAccountProviderIdOk returns a tuple with the SourceAccountProviderId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CostDataRecordDimensions) GetSourceAccountProviderIdOk() (*string, bool) {
	if o == nil || IsNil(o.SourceAccountProviderId) {
		return nil, false
	}
	return o.SourceAccountProviderId, true
}

// HasSourceAccountProviderId returns a boolean if a field has been set.
func (o *CostDataRecordDimensions) HasSourceAccountProviderId() bool {
	if o != nil && !IsNil(o.SourceAccountProviderId) {
		return true
	}

	return false
}

// SetSourceAccountProviderId gets a reference to the given string and assigns it to the SourceAccountProviderId field.
func (o *CostDataRecordDimensions) SetSourceAccountProviderId(v string) {
	o.SourceAccountProviderId = &v
}

func (o CostDataRecordDimensions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CostDataRecordDimensions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CloudProvider) {
		toSerialize["cloudProvider"] = o.CloudProvider
	}
	if !IsNil(o.ResourceType) {
		toSerialize["resourceType"] = o.ResourceType
	}
	if !IsNil(o.ResourceId) {
		toSerialize["resourceId"] = o.ResourceId
	}
	if !IsNil(o.SourceAccountProviderId) {
		toSerialize["sourceAccountProviderId"] = o.SourceAccountProviderId
	}
	return toSerialize, nil
}

type NullableCostDataRecordDimensions struct {
	value *CostDataRecordDimensions
	isSet bool
}

func (v NullableCostDataRecordDimensions) Get() *CostDataRecordDimensions {
	return v.value
}

func (v *NullableCostDataRecordDimensions) Set(val *CostDataRecordDimensions) {
	v.value = val
	v.isSet = true
}

func (v NullableCostDataRecordDimensions) IsSet() bool {
	return v.isSet
}

func (v *NullableCostDataRecordDimensions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCostDataRecordDimensions(val *CostDataRecordDimensions) *NullableCostDataRecordDimensions {
	return &NullableCostDataRecordDimensions{value: val, isSet: true}
}

func (v NullableCostDataRecordDimensions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCostDataRecordDimensions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


