/*
Eon API

The Eon.io REST API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eon

import (
	"encoding/json"
)

// checks if the FindingExclusionDetectorFilters type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FindingExclusionDetectorFilters{}

// FindingExclusionDetectorFilters Filters by the detector an exclusion suppresses.
type FindingExclusionDetectorFilters struct {
	// Matches exclusions for any of these detectors. An empty list applies no filter.
	In []FindingExclusionDetectorType `json:"in,omitempty"`
	// Matches exclusions for none of these detectors. An empty list applies no filter.
	NotIn []FindingExclusionDetectorType `json:"notIn,omitempty"`
}

// NewFindingExclusionDetectorFilters instantiates a new FindingExclusionDetectorFilters object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFindingExclusionDetectorFilters() *FindingExclusionDetectorFilters {
	this := FindingExclusionDetectorFilters{}
	return &this
}

// NewFindingExclusionDetectorFiltersWithDefaults instantiates a new FindingExclusionDetectorFilters object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFindingExclusionDetectorFiltersWithDefaults() *FindingExclusionDetectorFilters {
	this := FindingExclusionDetectorFilters{}
	return &this
}

// GetIn returns the In field value if set, zero value otherwise.
func (o *FindingExclusionDetectorFilters) GetIn() []FindingExclusionDetectorType {
	if o == nil || IsNil(o.In) {
		var ret []FindingExclusionDetectorType
		return ret
	}
	return o.In
}

// GetInOk returns a tuple with the In field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindingExclusionDetectorFilters) GetInOk() ([]FindingExclusionDetectorType, bool) {
	if o == nil || IsNil(o.In) {
		return nil, false
	}
	return o.In, true
}

// HasIn returns a boolean if a field has been set.
func (o *FindingExclusionDetectorFilters) HasIn() bool {
	if o != nil && !IsNil(o.In) {
		return true
	}

	return false
}

// SetIn gets a reference to the given []FindingExclusionDetectorType and assigns it to the In field.
func (o *FindingExclusionDetectorFilters) SetIn(v []FindingExclusionDetectorType) {
	o.In = v
}

// GetNotIn returns the NotIn field value if set, zero value otherwise.
func (o *FindingExclusionDetectorFilters) GetNotIn() []FindingExclusionDetectorType {
	if o == nil || IsNil(o.NotIn) {
		var ret []FindingExclusionDetectorType
		return ret
	}
	return o.NotIn
}

// GetNotInOk returns a tuple with the NotIn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FindingExclusionDetectorFilters) GetNotInOk() ([]FindingExclusionDetectorType, bool) {
	if o == nil || IsNil(o.NotIn) {
		return nil, false
	}
	return o.NotIn, true
}

// HasNotIn returns a boolean if a field has been set.
func (o *FindingExclusionDetectorFilters) HasNotIn() bool {
	if o != nil && !IsNil(o.NotIn) {
		return true
	}

	return false
}

// SetNotIn gets a reference to the given []FindingExclusionDetectorType and assigns it to the NotIn field.
func (o *FindingExclusionDetectorFilters) SetNotIn(v []FindingExclusionDetectorType) {
	o.NotIn = v
}

func (o FindingExclusionDetectorFilters) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FindingExclusionDetectorFilters) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.In) {
		toSerialize["in"] = o.In
	}
	if !IsNil(o.NotIn) {
		toSerialize["notIn"] = o.NotIn
	}
	return toSerialize, nil
}

type NullableFindingExclusionDetectorFilters struct {
	value *FindingExclusionDetectorFilters
	isSet bool
}

func (v NullableFindingExclusionDetectorFilters) Get() *FindingExclusionDetectorFilters {
	return v.value
}

func (v *NullableFindingExclusionDetectorFilters) Set(val *FindingExclusionDetectorFilters) {
	v.value = val
	v.isSet = true
}

func (v NullableFindingExclusionDetectorFilters) IsSet() bool {
	return v.isSet
}

func (v *NullableFindingExclusionDetectorFilters) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFindingExclusionDetectorFilters(val *FindingExclusionDetectorFilters) *NullableFindingExclusionDetectorFilters {
	return &NullableFindingExclusionDetectorFilters{value: val, isSet: true}
}

func (v NullableFindingExclusionDetectorFilters) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFindingExclusionDetectorFilters) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


