/*
Eon API

The Eon.io REST API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eon

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AwsDynamoDbResource type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AwsDynamoDbResource{}

// AwsDynamoDbResource struct for AwsDynamoDbResource
type AwsDynamoDbResource struct {
	BillingMode DynamoDbBillingMode `json:"billingMode"`
	// Provisioned read capacity units of the table.
	ReadCapacityUnits int64 `json:"readCapacityUnits"`
	// Provisioned write capacity units of the table.
	WriteCapacityUnits int64 `json:"writeCapacityUnits"`
	// Global secondary indexes on the table. Returned only when `include` contains `DYNAMODB_INDEXES`. 
	GlobalSecondaryIndexes []DynamoDbGlobalSecondaryIndex `json:"globalSecondaryIndexes,omitempty"`
	// Local secondary indexes on the table. Returned only when `include` contains `DYNAMODB_INDEXES`. 
	LocalSecondaryIndexes []DynamoDbLocalSecondaryIndex `json:"localSecondaryIndexes,omitempty"`
}

type _AwsDynamoDbResource AwsDynamoDbResource

// NewAwsDynamoDbResource instantiates a new AwsDynamoDbResource object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAwsDynamoDbResource(billingMode DynamoDbBillingMode, readCapacityUnits int64, writeCapacityUnits int64) *AwsDynamoDbResource {
	this := AwsDynamoDbResource{}
	this.BillingMode = billingMode
	this.ReadCapacityUnits = readCapacityUnits
	this.WriteCapacityUnits = writeCapacityUnits
	return &this
}

// NewAwsDynamoDbResourceWithDefaults instantiates a new AwsDynamoDbResource object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAwsDynamoDbResourceWithDefaults() *AwsDynamoDbResource {
	this := AwsDynamoDbResource{}
	return &this
}

// GetBillingMode returns the BillingMode field value
func (o *AwsDynamoDbResource) GetBillingMode() DynamoDbBillingMode {
	if o == nil {
		var ret DynamoDbBillingMode
		return ret
	}

	return o.BillingMode
}

// GetBillingModeOk returns a tuple with the BillingMode field value
// and a boolean to check if the value has been set.
func (o *AwsDynamoDbResource) GetBillingModeOk() (*DynamoDbBillingMode, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BillingMode, true
}

// SetBillingMode sets field value
func (o *AwsDynamoDbResource) SetBillingMode(v DynamoDbBillingMode) {
	o.BillingMode = v
}

// GetReadCapacityUnits returns the ReadCapacityUnits field value
func (o *AwsDynamoDbResource) GetReadCapacityUnits() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ReadCapacityUnits
}

// GetReadCapacityUnitsOk returns a tuple with the ReadCapacityUnits field value
// and a boolean to check if the value has been set.
func (o *AwsDynamoDbResource) GetReadCapacityUnitsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReadCapacityUnits, true
}

// SetReadCapacityUnits sets field value
func (o *AwsDynamoDbResource) SetReadCapacityUnits(v int64) {
	o.ReadCapacityUnits = v
}

// GetWriteCapacityUnits returns the WriteCapacityUnits field value
func (o *AwsDynamoDbResource) GetWriteCapacityUnits() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.WriteCapacityUnits
}

// GetWriteCapacityUnitsOk returns a tuple with the WriteCapacityUnits field value
// and a boolean to check if the value has been set.
func (o *AwsDynamoDbResource) GetWriteCapacityUnitsOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.WriteCapacityUnits, true
}

// SetWriteCapacityUnits sets field value
func (o *AwsDynamoDbResource) SetWriteCapacityUnits(v int64) {
	o.WriteCapacityUnits = v
}

// GetGlobalSecondaryIndexes returns the GlobalSecondaryIndexes field value if set, zero value otherwise.
func (o *AwsDynamoDbResource) GetGlobalSecondaryIndexes() []DynamoDbGlobalSecondaryIndex {
	if o == nil || IsNil(o.GlobalSecondaryIndexes) {
		var ret []DynamoDbGlobalSecondaryIndex
		return ret
	}
	return o.GlobalSecondaryIndexes
}

// GetGlobalSecondaryIndexesOk returns a tuple with the GlobalSecondaryIndexes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AwsDynamoDbResource) GetGlobalSecondaryIndexesOk() ([]DynamoDbGlobalSecondaryIndex, bool) {
	if o == nil || IsNil(o.GlobalSecondaryIndexes) {
		return nil, false
	}
	return o.GlobalSecondaryIndexes, true
}

// HasGlobalSecondaryIndexes returns a boolean if a field has been set.
func (o *AwsDynamoDbResource) HasGlobalSecondaryIndexes() bool {
	if o != nil && !IsNil(o.GlobalSecondaryIndexes) {
		return true
	}

	return false
}

// SetGlobalSecondaryIndexes gets a reference to the given []DynamoDbGlobalSecondaryIndex and assigns it to the GlobalSecondaryIndexes field.
func (o *AwsDynamoDbResource) SetGlobalSecondaryIndexes(v []DynamoDbGlobalSecondaryIndex) {
	o.GlobalSecondaryIndexes = v
}

// GetLocalSecondaryIndexes returns the LocalSecondaryIndexes field value if set, zero value otherwise.
func (o *AwsDynamoDbResource) GetLocalSecondaryIndexes() []DynamoDbLocalSecondaryIndex {
	if o == nil || IsNil(o.LocalSecondaryIndexes) {
		var ret []DynamoDbLocalSecondaryIndex
		return ret
	}
	return o.LocalSecondaryIndexes
}

// GetLocalSecondaryIndexesOk returns a tuple with the LocalSecondaryIndexes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AwsDynamoDbResource) GetLocalSecondaryIndexesOk() ([]DynamoDbLocalSecondaryIndex, bool) {
	if o == nil || IsNil(o.LocalSecondaryIndexes) {
		return nil, false
	}
	return o.LocalSecondaryIndexes, true
}

// HasLocalSecondaryIndexes returns a boolean if a field has been set.
func (o *AwsDynamoDbResource) HasLocalSecondaryIndexes() bool {
	if o != nil && !IsNil(o.LocalSecondaryIndexes) {
		return true
	}

	return false
}

// SetLocalSecondaryIndexes gets a reference to the given []DynamoDbLocalSecondaryIndex and assigns it to the LocalSecondaryIndexes field.
func (o *AwsDynamoDbResource) SetLocalSecondaryIndexes(v []DynamoDbLocalSecondaryIndex) {
	o.LocalSecondaryIndexes = v
}

func (o AwsDynamoDbResource) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AwsDynamoDbResource) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["billingMode"] = o.BillingMode
	toSerialize["readCapacityUnits"] = o.ReadCapacityUnits
	toSerialize["writeCapacityUnits"] = o.WriteCapacityUnits
	if !IsNil(o.GlobalSecondaryIndexes) {
		toSerialize["globalSecondaryIndexes"] = o.GlobalSecondaryIndexes
	}
	if !IsNil(o.LocalSecondaryIndexes) {
		toSerialize["localSecondaryIndexes"] = o.LocalSecondaryIndexes
	}
	return toSerialize, nil
}

func (o *AwsDynamoDbResource) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"billingMode",
		"readCapacityUnits",
		"writeCapacityUnits",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAwsDynamoDbResource := _AwsDynamoDbResource{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAwsDynamoDbResource)

	if err != nil {
		return err
	}

	*o = AwsDynamoDbResource(varAwsDynamoDbResource)

	return err
}

type NullableAwsDynamoDbResource struct {
	value *AwsDynamoDbResource
	isSet bool
}

func (v NullableAwsDynamoDbResource) Get() *AwsDynamoDbResource {
	return v.value
}

func (v *NullableAwsDynamoDbResource) Set(val *AwsDynamoDbResource) {
	v.value = val
	v.isSet = true
}

func (v NullableAwsDynamoDbResource) IsSet() bool {
	return v.isSet
}

func (v *NullableAwsDynamoDbResource) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAwsDynamoDbResource(val *AwsDynamoDbResource) *NullableAwsDynamoDbResource {
	return &NullableAwsDynamoDbResource{value: val, isSet: true}
}

func (v NullableAwsDynamoDbResource) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAwsDynamoDbResource) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


