/*
Eon API

The Eon.io REST API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eon

import (
	"encoding/json"
)

// checks if the RestoreAccountCloudAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RestoreAccountCloudAttributes{}

// RestoreAccountCloudAttributes struct for RestoreAccountCloudAttributes
type RestoreAccountCloudAttributes struct {
	CloudProvider *Provider `json:"cloudProvider,omitempty"`
	Aws NullableAwsRestoreAccountAttributes `json:"aws,omitempty"`
	Gcp NullableGcpRestoreAccountAttributes `json:"gcp,omitempty"`
	Azure NullableAzureRestoreAccountAttributes `json:"azure,omitempty"`
}

// NewRestoreAccountCloudAttributes instantiates a new RestoreAccountCloudAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRestoreAccountCloudAttributes() *RestoreAccountCloudAttributes {
	this := RestoreAccountCloudAttributes{}
	return &this
}

// NewRestoreAccountCloudAttributesWithDefaults instantiates a new RestoreAccountCloudAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRestoreAccountCloudAttributesWithDefaults() *RestoreAccountCloudAttributes {
	this := RestoreAccountCloudAttributes{}
	return &this
}

// GetCloudProvider returns the CloudProvider field value if set, zero value otherwise.
func (o *RestoreAccountCloudAttributes) GetCloudProvider() Provider {
	if o == nil || IsNil(o.CloudProvider) {
		var ret Provider
		return ret
	}
	return *o.CloudProvider
}

// GetCloudProviderOk returns a tuple with the CloudProvider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RestoreAccountCloudAttributes) GetCloudProviderOk() (*Provider, bool) {
	if o == nil || IsNil(o.CloudProvider) {
		return nil, false
	}
	return o.CloudProvider, true
}

// HasCloudProvider returns a boolean if a field has been set.
func (o *RestoreAccountCloudAttributes) HasCloudProvider() bool {
	if o != nil && !IsNil(o.CloudProvider) {
		return true
	}

	return false
}

// SetCloudProvider gets a reference to the given Provider and assigns it to the CloudProvider field.
func (o *RestoreAccountCloudAttributes) SetCloudProvider(v Provider) {
	o.CloudProvider = &v
}

// GetAws returns the Aws field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RestoreAccountCloudAttributes) GetAws() AwsRestoreAccountAttributes {
	if o == nil || IsNil(o.Aws.Get()) {
		var ret AwsRestoreAccountAttributes
		return ret
	}
	return *o.Aws.Get()
}

// GetAwsOk returns a tuple with the Aws field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RestoreAccountCloudAttributes) GetAwsOk() (*AwsRestoreAccountAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return o.Aws.Get(), o.Aws.IsSet()
}

// HasAws returns a boolean if a field has been set.
func (o *RestoreAccountCloudAttributes) HasAws() bool {
	if o != nil && o.Aws.IsSet() {
		return true
	}

	return false
}

// SetAws gets a reference to the given NullableAwsRestoreAccountAttributes and assigns it to the Aws field.
func (o *RestoreAccountCloudAttributes) SetAws(v AwsRestoreAccountAttributes) {
	o.Aws.Set(&v)
}
// SetAwsNil sets the value for Aws to be an explicit nil
func (o *RestoreAccountCloudAttributes) SetAwsNil() {
	o.Aws.Set(nil)
}

// UnsetAws ensures that no value is present for Aws, not even an explicit nil
func (o *RestoreAccountCloudAttributes) UnsetAws() {
	o.Aws.Unset()
}

// GetGcp returns the Gcp field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RestoreAccountCloudAttributes) GetGcp() GcpRestoreAccountAttributes {
	if o == nil || IsNil(o.Gcp.Get()) {
		var ret GcpRestoreAccountAttributes
		return ret
	}
	return *o.Gcp.Get()
}

// GetGcpOk returns a tuple with the Gcp field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RestoreAccountCloudAttributes) GetGcpOk() (*GcpRestoreAccountAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return o.Gcp.Get(), o.Gcp.IsSet()
}

// HasGcp returns a boolean if a field has been set.
func (o *RestoreAccountCloudAttributes) HasGcp() bool {
	if o != nil && o.Gcp.IsSet() {
		return true
	}

	return false
}

// SetGcp gets a reference to the given NullableGcpRestoreAccountAttributes and assigns it to the Gcp field.
func (o *RestoreAccountCloudAttributes) SetGcp(v GcpRestoreAccountAttributes) {
	o.Gcp.Set(&v)
}
// SetGcpNil sets the value for Gcp to be an explicit nil
func (o *RestoreAccountCloudAttributes) SetGcpNil() {
	o.Gcp.Set(nil)
}

// UnsetGcp ensures that no value is present for Gcp, not even an explicit nil
func (o *RestoreAccountCloudAttributes) UnsetGcp() {
	o.Gcp.Unset()
}

// GetAzure returns the Azure field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RestoreAccountCloudAttributes) GetAzure() AzureRestoreAccountAttributes {
	if o == nil || IsNil(o.Azure.Get()) {
		var ret AzureRestoreAccountAttributes
		return ret
	}
	return *o.Azure.Get()
}

// GetAzureOk returns a tuple with the Azure field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RestoreAccountCloudAttributes) GetAzureOk() (*AzureRestoreAccountAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return o.Azure.Get(), o.Azure.IsSet()
}

// HasAzure returns a boolean if a field has been set.
func (o *RestoreAccountCloudAttributes) HasAzure() bool {
	if o != nil && o.Azure.IsSet() {
		return true
	}

	return false
}

// SetAzure gets a reference to the given NullableAzureRestoreAccountAttributes and assigns it to the Azure field.
func (o *RestoreAccountCloudAttributes) SetAzure(v AzureRestoreAccountAttributes) {
	o.Azure.Set(&v)
}
// SetAzureNil sets the value for Azure to be an explicit nil
func (o *RestoreAccountCloudAttributes) SetAzureNil() {
	o.Azure.Set(nil)
}

// UnsetAzure ensures that no value is present for Azure, not even an explicit nil
func (o *RestoreAccountCloudAttributes) UnsetAzure() {
	o.Azure.Unset()
}

func (o RestoreAccountCloudAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RestoreAccountCloudAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CloudProvider) {
		toSerialize["cloudProvider"] = o.CloudProvider
	}
	if o.Aws.IsSet() {
		toSerialize["aws"] = o.Aws.Get()
	}
	if o.Gcp.IsSet() {
		toSerialize["gcp"] = o.Gcp.Get()
	}
	if o.Azure.IsSet() {
		toSerialize["azure"] = o.Azure.Get()
	}
	return toSerialize, nil
}

type NullableRestoreAccountCloudAttributes struct {
	value *RestoreAccountCloudAttributes
	isSet bool
}

func (v NullableRestoreAccountCloudAttributes) Get() *RestoreAccountCloudAttributes {
	return v.value
}

func (v *NullableRestoreAccountCloudAttributes) Set(val *RestoreAccountCloudAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableRestoreAccountCloudAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableRestoreAccountCloudAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRestoreAccountCloudAttributes(val *RestoreAccountCloudAttributes) *NullableRestoreAccountCloudAttributes {
	return &NullableRestoreAccountCloudAttributes{value: val, isSet: true}
}

func (v NullableRestoreAccountCloudAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRestoreAccountCloudAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


