/*
Eon API

The Eon.io REST API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eon

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GcpSourceAccountAttributesInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GcpSourceAccountAttributesInput{}

// GcpSourceAccountAttributesInput GCP project configuration. Applicable if `cloudProvider` is set to `GCP`. 
type GcpSourceAccountAttributesInput struct {
	// Email address of the GCP service account Eon uses to access the project.
	ServiceAccount string `json:"serviceAccount"`
}

type _GcpSourceAccountAttributesInput GcpSourceAccountAttributesInput

// NewGcpSourceAccountAttributesInput instantiates a new GcpSourceAccountAttributesInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGcpSourceAccountAttributesInput(serviceAccount string) *GcpSourceAccountAttributesInput {
	this := GcpSourceAccountAttributesInput{}
	this.ServiceAccount = serviceAccount
	return &this
}

// NewGcpSourceAccountAttributesInputWithDefaults instantiates a new GcpSourceAccountAttributesInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGcpSourceAccountAttributesInputWithDefaults() *GcpSourceAccountAttributesInput {
	this := GcpSourceAccountAttributesInput{}
	return &this
}

// GetServiceAccount returns the ServiceAccount field value
func (o *GcpSourceAccountAttributesInput) GetServiceAccount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ServiceAccount
}

// GetServiceAccountOk returns a tuple with the ServiceAccount field value
// and a boolean to check if the value has been set.
func (o *GcpSourceAccountAttributesInput) GetServiceAccountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceAccount, true
}

// SetServiceAccount sets field value
func (o *GcpSourceAccountAttributesInput) SetServiceAccount(v string) {
	o.ServiceAccount = v
}

func (o GcpSourceAccountAttributesInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GcpSourceAccountAttributesInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["serviceAccount"] = o.ServiceAccount
	return toSerialize, nil
}

func (o *GcpSourceAccountAttributesInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"serviceAccount",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGcpSourceAccountAttributesInput := _GcpSourceAccountAttributesInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGcpSourceAccountAttributesInput)

	if err != nil {
		return err
	}

	*o = GcpSourceAccountAttributesInput(varGcpSourceAccountAttributesInput)

	return err
}

type NullableGcpSourceAccountAttributesInput struct {
	value *GcpSourceAccountAttributesInput
	isSet bool
}

func (v NullableGcpSourceAccountAttributesInput) Get() *GcpSourceAccountAttributesInput {
	return v.value
}

func (v *NullableGcpSourceAccountAttributesInput) Set(val *GcpSourceAccountAttributesInput) {
	v.value = val
	v.isSet = true
}

func (v NullableGcpSourceAccountAttributesInput) IsSet() bool {
	return v.isSet
}

func (v *NullableGcpSourceAccountAttributesInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGcpSourceAccountAttributesInput(val *GcpSourceAccountAttributesInput) *NullableGcpSourceAccountAttributesInput {
	return &NullableGcpSourceAccountAttributesInput{value: val, isSet: true}
}

func (v NullableGcpSourceAccountAttributesInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGcpSourceAccountAttributesInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


