/*
Eon API

The Eon.io REST API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eon

import (
	"encoding/json"
	"fmt"
)

// Severity Severity assigned to a control and to the violations it raises.
type Severity string

// List of Severity
const (
	HIGH Severity = "HIGH"
	MEDIUM Severity = "MEDIUM"
	LOW Severity = "LOW"
)

// All allowed values of Severity enum
var AllowedSeverityEnumValues = []Severity{
	"HIGH",
	"MEDIUM",
	"LOW",
}

func (v *Severity) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	// x-extensible-enum (EON-15210): open set. Accept unknown values instead of failing so a
	// value added to the server's enum does not break decoding for an already-released client.
	*v = Severity(value)
	return nil
}

// NewSeverityFromValue returns a pointer to a valid Severity
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewSeverityFromValue(v string) (*Severity, error) {
	ev := Severity(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for Severity: valid values are %v", v, AllowedSeverityEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v Severity) IsValid() bool {
	for _, existing := range AllowedSeverityEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to Severity value
func (v Severity) Ptr() *Severity {
	return &v
}

type NullableSeverity struct {
	value *Severity
	isSet bool
}

func (v NullableSeverity) Get() *Severity {
	return v.value
}

func (v *NullableSeverity) Set(val *Severity) {
	v.value = val
	v.isSet = true
}

func (v NullableSeverity) IsSet() bool {
	return v.isSet
}

func (v *NullableSeverity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSeverity(val *Severity) *NullableSeverity {
	return &NullableSeverity{value: val, isSet: true}
}

func (v NullableSeverity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSeverity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

