/*
Eon API

The Eon.io REST API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eon

import (
	"encoding/json"
)

// checks if the EnableRestoreAccountMetricsConfigRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnableRestoreAccountMetricsConfigRequest{}

// EnableRestoreAccountMetricsConfigRequest struct for EnableRestoreAccountMetricsConfigRequest
type EnableRestoreAccountMetricsConfigRequest struct {
	Aws NullableAwsAccountMetricsDestination `json:"aws,omitempty"`
}

// NewEnableRestoreAccountMetricsConfigRequest instantiates a new EnableRestoreAccountMetricsConfigRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnableRestoreAccountMetricsConfigRequest() *EnableRestoreAccountMetricsConfigRequest {
	this := EnableRestoreAccountMetricsConfigRequest{}
	return &this
}

// NewEnableRestoreAccountMetricsConfigRequestWithDefaults instantiates a new EnableRestoreAccountMetricsConfigRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnableRestoreAccountMetricsConfigRequestWithDefaults() *EnableRestoreAccountMetricsConfigRequest {
	this := EnableRestoreAccountMetricsConfigRequest{}
	return &this
}

// GetAws returns the Aws field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EnableRestoreAccountMetricsConfigRequest) GetAws() AwsAccountMetricsDestination {
	if o == nil || IsNil(o.Aws.Get()) {
		var ret AwsAccountMetricsDestination
		return ret
	}
	return *o.Aws.Get()
}

// GetAwsOk returns a tuple with the Aws field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EnableRestoreAccountMetricsConfigRequest) GetAwsOk() (*AwsAccountMetricsDestination, bool) {
	if o == nil {
		return nil, false
	}
	return o.Aws.Get(), o.Aws.IsSet()
}

// HasAws returns a boolean if a field has been set.
func (o *EnableRestoreAccountMetricsConfigRequest) HasAws() bool {
	if o != nil && o.Aws.IsSet() {
		return true
	}

	return false
}

// SetAws gets a reference to the given NullableAwsAccountMetricsDestination and assigns it to the Aws field.
func (o *EnableRestoreAccountMetricsConfigRequest) SetAws(v AwsAccountMetricsDestination) {
	o.Aws.Set(&v)
}
// SetAwsNil sets the value for Aws to be an explicit nil
func (o *EnableRestoreAccountMetricsConfigRequest) SetAwsNil() {
	o.Aws.Set(nil)
}

// UnsetAws ensures that no value is present for Aws, not even an explicit nil
func (o *EnableRestoreAccountMetricsConfigRequest) UnsetAws() {
	o.Aws.Unset()
}

func (o EnableRestoreAccountMetricsConfigRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnableRestoreAccountMetricsConfigRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Aws.IsSet() {
		toSerialize["aws"] = o.Aws.Get()
	}
	return toSerialize, nil
}

type NullableEnableRestoreAccountMetricsConfigRequest struct {
	value *EnableRestoreAccountMetricsConfigRequest
	isSet bool
}

func (v NullableEnableRestoreAccountMetricsConfigRequest) Get() *EnableRestoreAccountMetricsConfigRequest {
	return v.value
}

func (v *NullableEnableRestoreAccountMetricsConfigRequest) Set(val *EnableRestoreAccountMetricsConfigRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEnableRestoreAccountMetricsConfigRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEnableRestoreAccountMetricsConfigRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnableRestoreAccountMetricsConfigRequest(val *EnableRestoreAccountMetricsConfigRequest) *NullableEnableRestoreAccountMetricsConfigRequest {
	return &NullableEnableRestoreAccountMetricsConfigRequest{value: val, isSet: true}
}

func (v NullableEnableRestoreAccountMetricsConfigRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnableRestoreAccountMetricsConfigRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


