/*
Eon API

The Eon.io REST API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eon

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SubnetConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubnetConfig{}

// SubnetConfig Subnet configuration for network interface creation
type SubnetConfig struct {
	// Whether to use an existing subnet or create a new one
	Mode string `json:"mode"`
	// Subnet name. Required when mode=existing. Optional when mode=create (defaults to eon-default-subnet-<region>). 
	Name *string `json:"name,omitempty"`
	// Address prefix in CIDR notation. Only used when mode=create. Defaults to 10.0.0.0/24 if not specified. 
	AddressPrefix *string `json:"addressPrefix,omitempty"`
}

type _SubnetConfig SubnetConfig

// NewSubnetConfig instantiates a new SubnetConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubnetConfig(mode string) *SubnetConfig {
	this := SubnetConfig{}
	this.Mode = mode
	return &this
}

// NewSubnetConfigWithDefaults instantiates a new SubnetConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubnetConfigWithDefaults() *SubnetConfig {
	this := SubnetConfig{}
	return &this
}

// GetMode returns the Mode field value
func (o *SubnetConfig) GetMode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Mode
}

// GetModeOk returns a tuple with the Mode field value
// and a boolean to check if the value has been set.
func (o *SubnetConfig) GetModeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Mode, true
}

// SetMode sets field value
func (o *SubnetConfig) SetMode(v string) {
	o.Mode = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *SubnetConfig) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubnetConfig) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SubnetConfig) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *SubnetConfig) SetName(v string) {
	o.Name = &v
}

// GetAddressPrefix returns the AddressPrefix field value if set, zero value otherwise.
func (o *SubnetConfig) GetAddressPrefix() string {
	if o == nil || IsNil(o.AddressPrefix) {
		var ret string
		return ret
	}
	return *o.AddressPrefix
}

// GetAddressPrefixOk returns a tuple with the AddressPrefix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubnetConfig) GetAddressPrefixOk() (*string, bool) {
	if o == nil || IsNil(o.AddressPrefix) {
		return nil, false
	}
	return o.AddressPrefix, true
}

// HasAddressPrefix returns a boolean if a field has been set.
func (o *SubnetConfig) HasAddressPrefix() bool {
	if o != nil && !IsNil(o.AddressPrefix) {
		return true
	}

	return false
}

// SetAddressPrefix gets a reference to the given string and assigns it to the AddressPrefix field.
func (o *SubnetConfig) SetAddressPrefix(v string) {
	o.AddressPrefix = &v
}

func (o SubnetConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubnetConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["mode"] = o.Mode
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.AddressPrefix) {
		toSerialize["addressPrefix"] = o.AddressPrefix
	}
	return toSerialize, nil
}

func (o *SubnetConfig) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"mode",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSubnetConfig := _SubnetConfig{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSubnetConfig)

	if err != nil {
		return err
	}

	*o = SubnetConfig(varSubnetConfig)

	return err
}

type NullableSubnetConfig struct {
	value *SubnetConfig
	isSet bool
}

func (v NullableSubnetConfig) Get() *SubnetConfig {
	return v.value
}

func (v *NullableSubnetConfig) Set(val *SubnetConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableSubnetConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableSubnetConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubnetConfig(val *SubnetConfig) *NullableSubnetConfig {
	return &NullableSubnetConfig{value: val, isSet: true}
}

func (v NullableSubnetConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubnetConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


