/*
Eon API

The Eon.io REST API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eon

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListBackupPostureControlsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListBackupPostureControlsResponse{}

// ListBackupPostureControlsResponse struct for ListBackupPostureControlsResponse
type ListBackupPostureControlsResponse struct {
	// List of retrieved backup posture controls.
	BackupPostureControls []BackupPostureControl `json:"backupPostureControls"`
	// Total number of backup posture controls that matched the filter options.
	TotalCount *int32 `json:"totalCount,omitempty"`
	// Cursor that points to the first record of the next page of results. Pass this value in the next request. 
	NextPageToken *string `json:"nextPageToken,omitempty"`
}

type _ListBackupPostureControlsResponse ListBackupPostureControlsResponse

// NewListBackupPostureControlsResponse instantiates a new ListBackupPostureControlsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListBackupPostureControlsResponse(backupPostureControls []BackupPostureControl) *ListBackupPostureControlsResponse {
	this := ListBackupPostureControlsResponse{}
	this.BackupPostureControls = backupPostureControls
	return &this
}

// NewListBackupPostureControlsResponseWithDefaults instantiates a new ListBackupPostureControlsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListBackupPostureControlsResponseWithDefaults() *ListBackupPostureControlsResponse {
	this := ListBackupPostureControlsResponse{}
	return &this
}

// GetBackupPostureControls returns the BackupPostureControls field value
func (o *ListBackupPostureControlsResponse) GetBackupPostureControls() []BackupPostureControl {
	if o == nil {
		var ret []BackupPostureControl
		return ret
	}

	return o.BackupPostureControls
}

// GetBackupPostureControlsOk returns a tuple with the BackupPostureControls field value
// and a boolean to check if the value has been set.
func (o *ListBackupPostureControlsResponse) GetBackupPostureControlsOk() ([]BackupPostureControl, bool) {
	if o == nil {
		return nil, false
	}
	return o.BackupPostureControls, true
}

// SetBackupPostureControls sets field value
func (o *ListBackupPostureControlsResponse) SetBackupPostureControls(v []BackupPostureControl) {
	o.BackupPostureControls = v
}

// GetTotalCount returns the TotalCount field value if set, zero value otherwise.
func (o *ListBackupPostureControlsResponse) GetTotalCount() int32 {
	if o == nil || IsNil(o.TotalCount) {
		var ret int32
		return ret
	}
	return *o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListBackupPostureControlsResponse) GetTotalCountOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalCount) {
		return nil, false
	}
	return o.TotalCount, true
}

// HasTotalCount returns a boolean if a field has been set.
func (o *ListBackupPostureControlsResponse) HasTotalCount() bool {
	if o != nil && !IsNil(o.TotalCount) {
		return true
	}

	return false
}

// SetTotalCount gets a reference to the given int32 and assigns it to the TotalCount field.
func (o *ListBackupPostureControlsResponse) SetTotalCount(v int32) {
	o.TotalCount = &v
}

// GetNextPageToken returns the NextPageToken field value if set, zero value otherwise.
func (o *ListBackupPostureControlsResponse) GetNextPageToken() string {
	if o == nil || IsNil(o.NextPageToken) {
		var ret string
		return ret
	}
	return *o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListBackupPostureControlsResponse) GetNextPageTokenOk() (*string, bool) {
	if o == nil || IsNil(o.NextPageToken) {
		return nil, false
	}
	return o.NextPageToken, true
}

// HasNextPageToken returns a boolean if a field has been set.
func (o *ListBackupPostureControlsResponse) HasNextPageToken() bool {
	if o != nil && !IsNil(o.NextPageToken) {
		return true
	}

	return false
}

// SetNextPageToken gets a reference to the given string and assigns it to the NextPageToken field.
func (o *ListBackupPostureControlsResponse) SetNextPageToken(v string) {
	o.NextPageToken = &v
}

func (o ListBackupPostureControlsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListBackupPostureControlsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["backupPostureControls"] = o.BackupPostureControls
	if !IsNil(o.TotalCount) {
		toSerialize["totalCount"] = o.TotalCount
	}
	if !IsNil(o.NextPageToken) {
		toSerialize["nextPageToken"] = o.NextPageToken
	}
	return toSerialize, nil
}

func (o *ListBackupPostureControlsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"backupPostureControls",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListBackupPostureControlsResponse := _ListBackupPostureControlsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListBackupPostureControlsResponse)

	if err != nil {
		return err
	}

	*o = ListBackupPostureControlsResponse(varListBackupPostureControlsResponse)

	return err
}

type NullableListBackupPostureControlsResponse struct {
	value *ListBackupPostureControlsResponse
	isSet bool
}

func (v NullableListBackupPostureControlsResponse) Get() *ListBackupPostureControlsResponse {
	return v.value
}

func (v *NullableListBackupPostureControlsResponse) Set(val *ListBackupPostureControlsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListBackupPostureControlsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListBackupPostureControlsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListBackupPostureControlsResponse(val *ListBackupPostureControlsResponse) *NullableListBackupPostureControlsResponse {
	return &NullableListBackupPostureControlsResponse{value: val, isSet: true}
}

func (v NullableListBackupPostureControlsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListBackupPostureControlsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


