/*
Eon API

The Eon.io REST API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eon

import (
	"encoding/json"
)

// checks if the ProviderOrganizationIdFilters type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProviderOrganizationIdFilters{}

// ProviderOrganizationIdFilters struct for ProviderOrganizationIdFilters
type ProviderOrganizationIdFilters struct {
	// Matches if any value in this list equals `providerOrganizationId`.
	In []string `json:"in,omitempty"`
	// Matches if none of the values in this list equal `providerOrganizationId`.
	NotIn []string `json:"notIn,omitempty"`
}

// NewProviderOrganizationIdFilters instantiates a new ProviderOrganizationIdFilters object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProviderOrganizationIdFilters() *ProviderOrganizationIdFilters {
	this := ProviderOrganizationIdFilters{}
	return &this
}

// NewProviderOrganizationIdFiltersWithDefaults instantiates a new ProviderOrganizationIdFilters object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProviderOrganizationIdFiltersWithDefaults() *ProviderOrganizationIdFilters {
	this := ProviderOrganizationIdFilters{}
	return &this
}

// GetIn returns the In field value if set, zero value otherwise.
func (o *ProviderOrganizationIdFilters) GetIn() []string {
	if o == nil || IsNil(o.In) {
		var ret []string
		return ret
	}
	return o.In
}

// GetInOk returns a tuple with the In field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderOrganizationIdFilters) GetInOk() ([]string, bool) {
	if o == nil || IsNil(o.In) {
		return nil, false
	}
	return o.In, true
}

// HasIn returns a boolean if a field has been set.
func (o *ProviderOrganizationIdFilters) HasIn() bool {
	if o != nil && !IsNil(o.In) {
		return true
	}

	return false
}

// SetIn gets a reference to the given []string and assigns it to the In field.
func (o *ProviderOrganizationIdFilters) SetIn(v []string) {
	o.In = v
}

// GetNotIn returns the NotIn field value if set, zero value otherwise.
func (o *ProviderOrganizationIdFilters) GetNotIn() []string {
	if o == nil || IsNil(o.NotIn) {
		var ret []string
		return ret
	}
	return o.NotIn
}

// GetNotInOk returns a tuple with the NotIn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProviderOrganizationIdFilters) GetNotInOk() ([]string, bool) {
	if o == nil || IsNil(o.NotIn) {
		return nil, false
	}
	return o.NotIn, true
}

// HasNotIn returns a boolean if a field has been set.
func (o *ProviderOrganizationIdFilters) HasNotIn() bool {
	if o != nil && !IsNil(o.NotIn) {
		return true
	}

	return false
}

// SetNotIn gets a reference to the given []string and assigns it to the NotIn field.
func (o *ProviderOrganizationIdFilters) SetNotIn(v []string) {
	o.NotIn = v
}

func (o ProviderOrganizationIdFilters) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProviderOrganizationIdFilters) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.In) {
		toSerialize["in"] = o.In
	}
	if !IsNil(o.NotIn) {
		toSerialize["notIn"] = o.NotIn
	}
	return toSerialize, nil
}

type NullableProviderOrganizationIdFilters struct {
	value *ProviderOrganizationIdFilters
	isSet bool
}

func (v NullableProviderOrganizationIdFilters) Get() *ProviderOrganizationIdFilters {
	return v.value
}

func (v *NullableProviderOrganizationIdFilters) Set(val *ProviderOrganizationIdFilters) {
	v.value = val
	v.isSet = true
}

func (v NullableProviderOrganizationIdFilters) IsSet() bool {
	return v.isSet
}

func (v *NullableProviderOrganizationIdFilters) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProviderOrganizationIdFilters(val *ProviderOrganizationIdFilters) *NullableProviderOrganizationIdFilters {
	return &NullableProviderOrganizationIdFilters{value: val, isSet: true}
}

func (v NullableProviderOrganizationIdFilters) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProviderOrganizationIdFilters) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


