/*
Eon API

The Eon.io REST API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eon

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EnableRestoreAccountMetricsConfigResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EnableRestoreAccountMetricsConfigResponse{}

// EnableRestoreAccountMetricsConfigResponse struct for EnableRestoreAccountMetricsConfigResponse
type EnableRestoreAccountMetricsConfigResponse struct {
	RestoreAccountConfig RestoreAccountMetricsConfig `json:"restoreAccountConfig"`
}

type _EnableRestoreAccountMetricsConfigResponse EnableRestoreAccountMetricsConfigResponse

// NewEnableRestoreAccountMetricsConfigResponse instantiates a new EnableRestoreAccountMetricsConfigResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEnableRestoreAccountMetricsConfigResponse(restoreAccountConfig RestoreAccountMetricsConfig) *EnableRestoreAccountMetricsConfigResponse {
	this := EnableRestoreAccountMetricsConfigResponse{}
	this.RestoreAccountConfig = restoreAccountConfig
	return &this
}

// NewEnableRestoreAccountMetricsConfigResponseWithDefaults instantiates a new EnableRestoreAccountMetricsConfigResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEnableRestoreAccountMetricsConfigResponseWithDefaults() *EnableRestoreAccountMetricsConfigResponse {
	this := EnableRestoreAccountMetricsConfigResponse{}
	return &this
}

// GetRestoreAccountConfig returns the RestoreAccountConfig field value
func (o *EnableRestoreAccountMetricsConfigResponse) GetRestoreAccountConfig() RestoreAccountMetricsConfig {
	if o == nil {
		var ret RestoreAccountMetricsConfig
		return ret
	}

	return o.RestoreAccountConfig
}

// GetRestoreAccountConfigOk returns a tuple with the RestoreAccountConfig field value
// and a boolean to check if the value has been set.
func (o *EnableRestoreAccountMetricsConfigResponse) GetRestoreAccountConfigOk() (*RestoreAccountMetricsConfig, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RestoreAccountConfig, true
}

// SetRestoreAccountConfig sets field value
func (o *EnableRestoreAccountMetricsConfigResponse) SetRestoreAccountConfig(v RestoreAccountMetricsConfig) {
	o.RestoreAccountConfig = v
}

func (o EnableRestoreAccountMetricsConfigResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EnableRestoreAccountMetricsConfigResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["restoreAccountConfig"] = o.RestoreAccountConfig
	return toSerialize, nil
}

func (o *EnableRestoreAccountMetricsConfigResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"restoreAccountConfig",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEnableRestoreAccountMetricsConfigResponse := _EnableRestoreAccountMetricsConfigResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEnableRestoreAccountMetricsConfigResponse)

	if err != nil {
		return err
	}

	*o = EnableRestoreAccountMetricsConfigResponse(varEnableRestoreAccountMetricsConfigResponse)

	return err
}

type NullableEnableRestoreAccountMetricsConfigResponse struct {
	value *EnableRestoreAccountMetricsConfigResponse
	isSet bool
}

func (v NullableEnableRestoreAccountMetricsConfigResponse) Get() *EnableRestoreAccountMetricsConfigResponse {
	return v.value
}

func (v *NullableEnableRestoreAccountMetricsConfigResponse) Set(val *EnableRestoreAccountMetricsConfigResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableEnableRestoreAccountMetricsConfigResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableEnableRestoreAccountMetricsConfigResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEnableRestoreAccountMetricsConfigResponse(val *EnableRestoreAccountMetricsConfigResponse) *NullableEnableRestoreAccountMetricsConfigResponse {
	return &NullableEnableRestoreAccountMetricsConfigResponse{value: val, isSet: true}
}

func (v NullableEnableRestoreAccountMetricsConfigResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEnableRestoreAccountMetricsConfigResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


