/*
Eon API

The Eon.io REST API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eon

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AwsNativeStandardBackupPolicyPlan type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AwsNativeStandardBackupPolicyPlan{}

// AwsNativeStandardBackupPolicyPlan struct for AwsNativeStandardBackupPolicyPlan
type AwsNativeStandardBackupPolicyPlan struct {
	// List of backup schedules. Each schedule specifies a backup frequency, retention period, and target region. 
	BackupSchedules []AwsNativeStandardBackupSchedules `json:"backupSchedules"`
	VaultProtectionMode *VaultProtectionMode `json:"vaultProtectionMode,omitempty"`
}

type _AwsNativeStandardBackupPolicyPlan AwsNativeStandardBackupPolicyPlan

// NewAwsNativeStandardBackupPolicyPlan instantiates a new AwsNativeStandardBackupPolicyPlan object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAwsNativeStandardBackupPolicyPlan(backupSchedules []AwsNativeStandardBackupSchedules) *AwsNativeStandardBackupPolicyPlan {
	this := AwsNativeStandardBackupPolicyPlan{}
	this.BackupSchedules = backupSchedules
	return &this
}

// NewAwsNativeStandardBackupPolicyPlanWithDefaults instantiates a new AwsNativeStandardBackupPolicyPlan object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAwsNativeStandardBackupPolicyPlanWithDefaults() *AwsNativeStandardBackupPolicyPlan {
	this := AwsNativeStandardBackupPolicyPlan{}
	return &this
}

// GetBackupSchedules returns the BackupSchedules field value
func (o *AwsNativeStandardBackupPolicyPlan) GetBackupSchedules() []AwsNativeStandardBackupSchedules {
	if o == nil {
		var ret []AwsNativeStandardBackupSchedules
		return ret
	}

	return o.BackupSchedules
}

// GetBackupSchedulesOk returns a tuple with the BackupSchedules field value
// and a boolean to check if the value has been set.
func (o *AwsNativeStandardBackupPolicyPlan) GetBackupSchedulesOk() ([]AwsNativeStandardBackupSchedules, bool) {
	if o == nil {
		return nil, false
	}
	return o.BackupSchedules, true
}

// SetBackupSchedules sets field value
func (o *AwsNativeStandardBackupPolicyPlan) SetBackupSchedules(v []AwsNativeStandardBackupSchedules) {
	o.BackupSchedules = v
}

// GetVaultProtectionMode returns the VaultProtectionMode field value if set, zero value otherwise.
func (o *AwsNativeStandardBackupPolicyPlan) GetVaultProtectionMode() VaultProtectionMode {
	if o == nil || IsNil(o.VaultProtectionMode) {
		var ret VaultProtectionMode
		return ret
	}
	return *o.VaultProtectionMode
}

// GetVaultProtectionModeOk returns a tuple with the VaultProtectionMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AwsNativeStandardBackupPolicyPlan) GetVaultProtectionModeOk() (*VaultProtectionMode, bool) {
	if o == nil || IsNil(o.VaultProtectionMode) {
		return nil, false
	}
	return o.VaultProtectionMode, true
}

// HasVaultProtectionMode returns a boolean if a field has been set.
func (o *AwsNativeStandardBackupPolicyPlan) HasVaultProtectionMode() bool {
	if o != nil && !IsNil(o.VaultProtectionMode) {
		return true
	}

	return false
}

// SetVaultProtectionMode gets a reference to the given VaultProtectionMode and assigns it to the VaultProtectionMode field.
func (o *AwsNativeStandardBackupPolicyPlan) SetVaultProtectionMode(v VaultProtectionMode) {
	o.VaultProtectionMode = &v
}

func (o AwsNativeStandardBackupPolicyPlan) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AwsNativeStandardBackupPolicyPlan) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["backupSchedules"] = o.BackupSchedules
	if !IsNil(o.VaultProtectionMode) {
		toSerialize["vaultProtectionMode"] = o.VaultProtectionMode
	}
	return toSerialize, nil
}

func (o *AwsNativeStandardBackupPolicyPlan) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"backupSchedules",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAwsNativeStandardBackupPolicyPlan := _AwsNativeStandardBackupPolicyPlan{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAwsNativeStandardBackupPolicyPlan)

	if err != nil {
		return err
	}

	*o = AwsNativeStandardBackupPolicyPlan(varAwsNativeStandardBackupPolicyPlan)

	return err
}

type NullableAwsNativeStandardBackupPolicyPlan struct {
	value *AwsNativeStandardBackupPolicyPlan
	isSet bool
}

func (v NullableAwsNativeStandardBackupPolicyPlan) Get() *AwsNativeStandardBackupPolicyPlan {
	return v.value
}

func (v *NullableAwsNativeStandardBackupPolicyPlan) Set(val *AwsNativeStandardBackupPolicyPlan) {
	v.value = val
	v.isSet = true
}

func (v NullableAwsNativeStandardBackupPolicyPlan) IsSet() bool {
	return v.isSet
}

func (v *NullableAwsNativeStandardBackupPolicyPlan) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAwsNativeStandardBackupPolicyPlan(val *AwsNativeStandardBackupPolicyPlan) *NullableAwsNativeStandardBackupPolicyPlan {
	return &NullableAwsNativeStandardBackupPolicyPlan{value: val, isSet: true}
}

func (v NullableAwsNativeStandardBackupPolicyPlan) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAwsNativeStandardBackupPolicyPlan) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


