/*
Eon API

The Eon.io REST API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eon

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateBackupPostureControlRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateBackupPostureControlRequest{}

// CreateBackupPostureControlRequest struct for CreateBackupPostureControlRequest
type CreateBackupPostureControlRequest struct {
	// Display name of the control.
	Name string `json:"name"`
	Severity Severity `json:"severity"`
	ResourceSelector NullableBackupPostureControlResourceSelector `json:"resourceSelector"`
	Rules NullableBackupPostureControlRules `json:"rules"`
}

type _CreateBackupPostureControlRequest CreateBackupPostureControlRequest

// NewCreateBackupPostureControlRequest instantiates a new CreateBackupPostureControlRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateBackupPostureControlRequest(name string, severity Severity, resourceSelector NullableBackupPostureControlResourceSelector, rules NullableBackupPostureControlRules) *CreateBackupPostureControlRequest {
	this := CreateBackupPostureControlRequest{}
	this.Name = name
	this.Severity = severity
	this.ResourceSelector = resourceSelector
	this.Rules = rules
	return &this
}

// NewCreateBackupPostureControlRequestWithDefaults instantiates a new CreateBackupPostureControlRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateBackupPostureControlRequestWithDefaults() *CreateBackupPostureControlRequest {
	this := CreateBackupPostureControlRequest{}
	return &this
}

// GetName returns the Name field value
func (o *CreateBackupPostureControlRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateBackupPostureControlRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateBackupPostureControlRequest) SetName(v string) {
	o.Name = v
}

// GetSeverity returns the Severity field value
func (o *CreateBackupPostureControlRequest) GetSeverity() Severity {
	if o == nil {
		var ret Severity
		return ret
	}

	return o.Severity
}

// GetSeverityOk returns a tuple with the Severity field value
// and a boolean to check if the value has been set.
func (o *CreateBackupPostureControlRequest) GetSeverityOk() (*Severity, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Severity, true
}

// SetSeverity sets field value
func (o *CreateBackupPostureControlRequest) SetSeverity(v Severity) {
	o.Severity = v
}

// GetResourceSelector returns the ResourceSelector field value
// If the value is explicit nil, the zero value for BackupPostureControlResourceSelector will be returned
func (o *CreateBackupPostureControlRequest) GetResourceSelector() BackupPostureControlResourceSelector {
	if o == nil || o.ResourceSelector.Get() == nil {
		var ret BackupPostureControlResourceSelector
		return ret
	}

	return *o.ResourceSelector.Get()
}

// GetResourceSelectorOk returns a tuple with the ResourceSelector field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateBackupPostureControlRequest) GetResourceSelectorOk() (*BackupPostureControlResourceSelector, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResourceSelector.Get(), o.ResourceSelector.IsSet()
}

// SetResourceSelector sets field value
func (o *CreateBackupPostureControlRequest) SetResourceSelector(v BackupPostureControlResourceSelector) {
	o.ResourceSelector.Set(&v)
}

// GetRules returns the Rules field value
// If the value is explicit nil, the zero value for BackupPostureControlRules will be returned
func (o *CreateBackupPostureControlRequest) GetRules() BackupPostureControlRules {
	if o == nil || o.Rules.Get() == nil {
		var ret BackupPostureControlRules
		return ret
	}

	return *o.Rules.Get()
}

// GetRulesOk returns a tuple with the Rules field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateBackupPostureControlRequest) GetRulesOk() (*BackupPostureControlRules, bool) {
	if o == nil {
		return nil, false
	}
	return o.Rules.Get(), o.Rules.IsSet()
}

// SetRules sets field value
func (o *CreateBackupPostureControlRequest) SetRules(v BackupPostureControlRules) {
	o.Rules.Set(&v)
}

func (o CreateBackupPostureControlRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateBackupPostureControlRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["severity"] = o.Severity
	toSerialize["resourceSelector"] = o.ResourceSelector.Get()
	toSerialize["rules"] = o.Rules.Get()
	return toSerialize, nil
}

func (o *CreateBackupPostureControlRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"severity",
		"resourceSelector",
		"rules",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateBackupPostureControlRequest := _CreateBackupPostureControlRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateBackupPostureControlRequest)

	if err != nil {
		return err
	}

	*o = CreateBackupPostureControlRequest(varCreateBackupPostureControlRequest)

	return err
}

type NullableCreateBackupPostureControlRequest struct {
	value *CreateBackupPostureControlRequest
	isSet bool
}

func (v NullableCreateBackupPostureControlRequest) Get() *CreateBackupPostureControlRequest {
	return v.value
}

func (v *NullableCreateBackupPostureControlRequest) Set(val *CreateBackupPostureControlRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateBackupPostureControlRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateBackupPostureControlRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateBackupPostureControlRequest(val *CreateBackupPostureControlRequest) *NullableCreateBackupPostureControlRequest {
	return &NullableCreateBackupPostureControlRequest{value: val, isSet: true}
}

func (v NullableCreateBackupPostureControlRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateBackupPostureControlRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


