/*
Eon API

The Eon.io REST API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eon

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetRestoreJobResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetRestoreJobResponse{}

// GetRestoreJobResponse struct for GetRestoreJobResponse
type GetRestoreJobResponse struct {
	Job RestoreJob `json:"job"`
}

type _GetRestoreJobResponse GetRestoreJobResponse

// NewGetRestoreJobResponse instantiates a new GetRestoreJobResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetRestoreJobResponse(job RestoreJob) *GetRestoreJobResponse {
	this := GetRestoreJobResponse{}
	this.Job = job
	return &this
}

// NewGetRestoreJobResponseWithDefaults instantiates a new GetRestoreJobResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRestoreJobResponseWithDefaults() *GetRestoreJobResponse {
	this := GetRestoreJobResponse{}
	return &this
}

// GetJob returns the Job field value
func (o *GetRestoreJobResponse) GetJob() RestoreJob {
	if o == nil {
		var ret RestoreJob
		return ret
	}

	return o.Job
}

// GetJobOk returns a tuple with the Job field value
// and a boolean to check if the value has been set.
func (o *GetRestoreJobResponse) GetJobOk() (*RestoreJob, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Job, true
}

// SetJob sets field value
func (o *GetRestoreJobResponse) SetJob(v RestoreJob) {
	o.Job = v
}

func (o GetRestoreJobResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetRestoreJobResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["job"] = o.Job
	return toSerialize, nil
}

func (o *GetRestoreJobResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"job",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetRestoreJobResponse := _GetRestoreJobResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	// Allow unknown fields to handle API schema differences
	// // Allow unknown fields to handle API schema differences
	// decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetRestoreJobResponse)

	if err != nil {
		return err
	}

	*o = GetRestoreJobResponse(varGetRestoreJobResponse)

	return err
}

type NullableGetRestoreJobResponse struct {
	value *GetRestoreJobResponse
	isSet bool
}

func (v NullableGetRestoreJobResponse) Get() *GetRestoreJobResponse {
	return v.value
}

func (v *NullableGetRestoreJobResponse) Set(val *GetRestoreJobResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRestoreJobResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRestoreJobResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRestoreJobResponse(val *GetRestoreJobResponse) *NullableGetRestoreJobResponse {
	return &NullableGetRestoreJobResponse{value: val, isSet: true}
}

func (v NullableGetRestoreJobResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRestoreJobResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


