/*
Eon API

The Eon.io REST API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eon

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GcpRestoreAccountAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GcpRestoreAccountAttributes{}

// GcpRestoreAccountAttributes struct for GcpRestoreAccountAttributes
type GcpRestoreAccountAttributes struct {
	ServiceAccount string `json:"serviceAccount"`
}

type _GcpRestoreAccountAttributes GcpRestoreAccountAttributes

// NewGcpRestoreAccountAttributes instantiates a new GcpRestoreAccountAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGcpRestoreAccountAttributes(serviceAccount string) *GcpRestoreAccountAttributes {
	this := GcpRestoreAccountAttributes{}
	this.ServiceAccount = serviceAccount
	return &this
}

// NewGcpRestoreAccountAttributesWithDefaults instantiates a new GcpRestoreAccountAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGcpRestoreAccountAttributesWithDefaults() *GcpRestoreAccountAttributes {
	this := GcpRestoreAccountAttributes{}
	return &this
}

// GetServiceAccount returns the ServiceAccount field value
func (o *GcpRestoreAccountAttributes) GetServiceAccount() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ServiceAccount
}

// GetServiceAccountOk returns a tuple with the ServiceAccount field value
// and a boolean to check if the value has been set.
func (o *GcpRestoreAccountAttributes) GetServiceAccountOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceAccount, true
}

// SetServiceAccount sets field value
func (o *GcpRestoreAccountAttributes) SetServiceAccount(v string) {
	o.ServiceAccount = v
}

func (o GcpRestoreAccountAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GcpRestoreAccountAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["serviceAccount"] = o.ServiceAccount
	return toSerialize, nil
}

func (o *GcpRestoreAccountAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"serviceAccount",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGcpRestoreAccountAttributes := _GcpRestoreAccountAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGcpRestoreAccountAttributes)

	if err != nil {
		return err
	}

	*o = GcpRestoreAccountAttributes(varGcpRestoreAccountAttributes)

	return err
}

type NullableGcpRestoreAccountAttributes struct {
	value *GcpRestoreAccountAttributes
	isSet bool
}

func (v NullableGcpRestoreAccountAttributes) Get() *GcpRestoreAccountAttributes {
	return v.value
}

func (v *NullableGcpRestoreAccountAttributes) Set(val *GcpRestoreAccountAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableGcpRestoreAccountAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableGcpRestoreAccountAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGcpRestoreAccountAttributes(val *GcpRestoreAccountAttributes) *NullableGcpRestoreAccountAttributes {
	return &NullableGcpRestoreAccountAttributes{value: val, isSet: true}
}

func (v NullableGcpRestoreAccountAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGcpRestoreAccountAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


