/*
Eon API

The Eon.io REST API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eon

import (
	"encoding/json"
)

// checks if the BackupPostureControlExpression type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BackupPostureControlExpression{}

// BackupPostureControlExpression Resource selector expression that determines which resources a backup posture control applies to. Set exactly one of the properties below. For AND/OR logic across multiple conditions, use `group`; groups can be nested. 
type BackupPostureControlExpression struct {
	Group NullableBackupPostureControlGroupCondition `json:"group,omitempty"`
	ResourceType NullableResourceTypeCondition `json:"resourceType,omitempty"`
	DataClasses NullableDataClassesCondition `json:"dataClasses,omitempty"`
	Environment NullableEnvironmentCondition `json:"environment,omitempty"`
	Apps NullableAppsCondition `json:"apps,omitempty"`
	CloudProvider NullableCloudProviderCondition `json:"cloudProvider,omitempty"`
	AccountId NullableAccountIdCondition `json:"accountId,omitempty"`
	SourceRegion NullableRegionCondition `json:"sourceRegion,omitempty"`
	Vpc NullableVpcCondition `json:"vpc,omitempty"`
	Subnets NullableSubnetsCondition `json:"subnets,omitempty"`
	ResourceGroupName NullableResourceGroupNameCondition `json:"resourceGroupName,omitempty"`
	ResourceName NullableResourceNameCondition `json:"resourceName,omitempty"`
	ResourceId NullableResourceIdCondition `json:"resourceId,omitempty"`
	TagKeys NullableTagKeysCondition `json:"tagKeys,omitempty"`
	TagKeyValues NullableTagKeyValuesCondition `json:"tagKeyValues,omitempty"`
}

// NewBackupPostureControlExpression instantiates a new BackupPostureControlExpression object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBackupPostureControlExpression() *BackupPostureControlExpression {
	this := BackupPostureControlExpression{}
	return &this
}

// NewBackupPostureControlExpressionWithDefaults instantiates a new BackupPostureControlExpression object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBackupPostureControlExpressionWithDefaults() *BackupPostureControlExpression {
	this := BackupPostureControlExpression{}
	return &this
}

// GetGroup returns the Group field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BackupPostureControlExpression) GetGroup() BackupPostureControlGroupCondition {
	if o == nil || IsNil(o.Group.Get()) {
		var ret BackupPostureControlGroupCondition
		return ret
	}
	return *o.Group.Get()
}

// GetGroupOk returns a tuple with the Group field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BackupPostureControlExpression) GetGroupOk() (*BackupPostureControlGroupCondition, bool) {
	if o == nil {
		return nil, false
	}
	return o.Group.Get(), o.Group.IsSet()
}

// HasGroup returns a boolean if a field has been set.
func (o *BackupPostureControlExpression) HasGroup() bool {
	if o != nil && o.Group.IsSet() {
		return true
	}

	return false
}

// SetGroup gets a reference to the given NullableBackupPostureControlGroupCondition and assigns it to the Group field.
func (o *BackupPostureControlExpression) SetGroup(v BackupPostureControlGroupCondition) {
	o.Group.Set(&v)
}
// SetGroupNil sets the value for Group to be an explicit nil
func (o *BackupPostureControlExpression) SetGroupNil() {
	o.Group.Set(nil)
}

// UnsetGroup ensures that no value is present for Group, not even an explicit nil
func (o *BackupPostureControlExpression) UnsetGroup() {
	o.Group.Unset()
}

// GetResourceType returns the ResourceType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BackupPostureControlExpression) GetResourceType() ResourceTypeCondition {
	if o == nil || IsNil(o.ResourceType.Get()) {
		var ret ResourceTypeCondition
		return ret
	}
	return *o.ResourceType.Get()
}

// GetResourceTypeOk returns a tuple with the ResourceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BackupPostureControlExpression) GetResourceTypeOk() (*ResourceTypeCondition, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResourceType.Get(), o.ResourceType.IsSet()
}

// HasResourceType returns a boolean if a field has been set.
func (o *BackupPostureControlExpression) HasResourceType() bool {
	if o != nil && o.ResourceType.IsSet() {
		return true
	}

	return false
}

// SetResourceType gets a reference to the given NullableResourceTypeCondition and assigns it to the ResourceType field.
func (o *BackupPostureControlExpression) SetResourceType(v ResourceTypeCondition) {
	o.ResourceType.Set(&v)
}
// SetResourceTypeNil sets the value for ResourceType to be an explicit nil
func (o *BackupPostureControlExpression) SetResourceTypeNil() {
	o.ResourceType.Set(nil)
}

// UnsetResourceType ensures that no value is present for ResourceType, not even an explicit nil
func (o *BackupPostureControlExpression) UnsetResourceType() {
	o.ResourceType.Unset()
}

// GetDataClasses returns the DataClasses field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BackupPostureControlExpression) GetDataClasses() DataClassesCondition {
	if o == nil || IsNil(o.DataClasses.Get()) {
		var ret DataClassesCondition
		return ret
	}
	return *o.DataClasses.Get()
}

// GetDataClassesOk returns a tuple with the DataClasses field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BackupPostureControlExpression) GetDataClassesOk() (*DataClassesCondition, bool) {
	if o == nil {
		return nil, false
	}
	return o.DataClasses.Get(), o.DataClasses.IsSet()
}

// HasDataClasses returns a boolean if a field has been set.
func (o *BackupPostureControlExpression) HasDataClasses() bool {
	if o != nil && o.DataClasses.IsSet() {
		return true
	}

	return false
}

// SetDataClasses gets a reference to the given NullableDataClassesCondition and assigns it to the DataClasses field.
func (o *BackupPostureControlExpression) SetDataClasses(v DataClassesCondition) {
	o.DataClasses.Set(&v)
}
// SetDataClassesNil sets the value for DataClasses to be an explicit nil
func (o *BackupPostureControlExpression) SetDataClassesNil() {
	o.DataClasses.Set(nil)
}

// UnsetDataClasses ensures that no value is present for DataClasses, not even an explicit nil
func (o *BackupPostureControlExpression) UnsetDataClasses() {
	o.DataClasses.Unset()
}

// GetEnvironment returns the Environment field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BackupPostureControlExpression) GetEnvironment() EnvironmentCondition {
	if o == nil || IsNil(o.Environment.Get()) {
		var ret EnvironmentCondition
		return ret
	}
	return *o.Environment.Get()
}

// GetEnvironmentOk returns a tuple with the Environment field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BackupPostureControlExpression) GetEnvironmentOk() (*EnvironmentCondition, bool) {
	if o == nil {
		return nil, false
	}
	return o.Environment.Get(), o.Environment.IsSet()
}

// HasEnvironment returns a boolean if a field has been set.
func (o *BackupPostureControlExpression) HasEnvironment() bool {
	if o != nil && o.Environment.IsSet() {
		return true
	}

	return false
}

// SetEnvironment gets a reference to the given NullableEnvironmentCondition and assigns it to the Environment field.
func (o *BackupPostureControlExpression) SetEnvironment(v EnvironmentCondition) {
	o.Environment.Set(&v)
}
// SetEnvironmentNil sets the value for Environment to be an explicit nil
func (o *BackupPostureControlExpression) SetEnvironmentNil() {
	o.Environment.Set(nil)
}

// UnsetEnvironment ensures that no value is present for Environment, not even an explicit nil
func (o *BackupPostureControlExpression) UnsetEnvironment() {
	o.Environment.Unset()
}

// GetApps returns the Apps field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BackupPostureControlExpression) GetApps() AppsCondition {
	if o == nil || IsNil(o.Apps.Get()) {
		var ret AppsCondition
		return ret
	}
	return *o.Apps.Get()
}

// GetAppsOk returns a tuple with the Apps field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BackupPostureControlExpression) GetAppsOk() (*AppsCondition, bool) {
	if o == nil {
		return nil, false
	}
	return o.Apps.Get(), o.Apps.IsSet()
}

// HasApps returns a boolean if a field has been set.
func (o *BackupPostureControlExpression) HasApps() bool {
	if o != nil && o.Apps.IsSet() {
		return true
	}

	return false
}

// SetApps gets a reference to the given NullableAppsCondition and assigns it to the Apps field.
func (o *BackupPostureControlExpression) SetApps(v AppsCondition) {
	o.Apps.Set(&v)
}
// SetAppsNil sets the value for Apps to be an explicit nil
func (o *BackupPostureControlExpression) SetAppsNil() {
	o.Apps.Set(nil)
}

// UnsetApps ensures that no value is present for Apps, not even an explicit nil
func (o *BackupPostureControlExpression) UnsetApps() {
	o.Apps.Unset()
}

// GetCloudProvider returns the CloudProvider field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BackupPostureControlExpression) GetCloudProvider() CloudProviderCondition {
	if o == nil || IsNil(o.CloudProvider.Get()) {
		var ret CloudProviderCondition
		return ret
	}
	return *o.CloudProvider.Get()
}

// GetCloudProviderOk returns a tuple with the CloudProvider field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BackupPostureControlExpression) GetCloudProviderOk() (*CloudProviderCondition, bool) {
	if o == nil {
		return nil, false
	}
	return o.CloudProvider.Get(), o.CloudProvider.IsSet()
}

// HasCloudProvider returns a boolean if a field has been set.
func (o *BackupPostureControlExpression) HasCloudProvider() bool {
	if o != nil && o.CloudProvider.IsSet() {
		return true
	}

	return false
}

// SetCloudProvider gets a reference to the given NullableCloudProviderCondition and assigns it to the CloudProvider field.
func (o *BackupPostureControlExpression) SetCloudProvider(v CloudProviderCondition) {
	o.CloudProvider.Set(&v)
}
// SetCloudProviderNil sets the value for CloudProvider to be an explicit nil
func (o *BackupPostureControlExpression) SetCloudProviderNil() {
	o.CloudProvider.Set(nil)
}

// UnsetCloudProvider ensures that no value is present for CloudProvider, not even an explicit nil
func (o *BackupPostureControlExpression) UnsetCloudProvider() {
	o.CloudProvider.Unset()
}

// GetAccountId returns the AccountId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BackupPostureControlExpression) GetAccountId() AccountIdCondition {
	if o == nil || IsNil(o.AccountId.Get()) {
		var ret AccountIdCondition
		return ret
	}
	return *o.AccountId.Get()
}

// GetAccountIdOk returns a tuple with the AccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BackupPostureControlExpression) GetAccountIdOk() (*AccountIdCondition, bool) {
	if o == nil {
		return nil, false
	}
	return o.AccountId.Get(), o.AccountId.IsSet()
}

// HasAccountId returns a boolean if a field has been set.
func (o *BackupPostureControlExpression) HasAccountId() bool {
	if o != nil && o.AccountId.IsSet() {
		return true
	}

	return false
}

// SetAccountId gets a reference to the given NullableAccountIdCondition and assigns it to the AccountId field.
func (o *BackupPostureControlExpression) SetAccountId(v AccountIdCondition) {
	o.AccountId.Set(&v)
}
// SetAccountIdNil sets the value for AccountId to be an explicit nil
func (o *BackupPostureControlExpression) SetAccountIdNil() {
	o.AccountId.Set(nil)
}

// UnsetAccountId ensures that no value is present for AccountId, not even an explicit nil
func (o *BackupPostureControlExpression) UnsetAccountId() {
	o.AccountId.Unset()
}

// GetSourceRegion returns the SourceRegion field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BackupPostureControlExpression) GetSourceRegion() RegionCondition {
	if o == nil || IsNil(o.SourceRegion.Get()) {
		var ret RegionCondition
		return ret
	}
	return *o.SourceRegion.Get()
}

// GetSourceRegionOk returns a tuple with the SourceRegion field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BackupPostureControlExpression) GetSourceRegionOk() (*RegionCondition, bool) {
	if o == nil {
		return nil, false
	}
	return o.SourceRegion.Get(), o.SourceRegion.IsSet()
}

// HasSourceRegion returns a boolean if a field has been set.
func (o *BackupPostureControlExpression) HasSourceRegion() bool {
	if o != nil && o.SourceRegion.IsSet() {
		return true
	}

	return false
}

// SetSourceRegion gets a reference to the given NullableRegionCondition and assigns it to the SourceRegion field.
func (o *BackupPostureControlExpression) SetSourceRegion(v RegionCondition) {
	o.SourceRegion.Set(&v)
}
// SetSourceRegionNil sets the value for SourceRegion to be an explicit nil
func (o *BackupPostureControlExpression) SetSourceRegionNil() {
	o.SourceRegion.Set(nil)
}

// UnsetSourceRegion ensures that no value is present for SourceRegion, not even an explicit nil
func (o *BackupPostureControlExpression) UnsetSourceRegion() {
	o.SourceRegion.Unset()
}

// GetVpc returns the Vpc field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BackupPostureControlExpression) GetVpc() VpcCondition {
	if o == nil || IsNil(o.Vpc.Get()) {
		var ret VpcCondition
		return ret
	}
	return *o.Vpc.Get()
}

// GetVpcOk returns a tuple with the Vpc field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BackupPostureControlExpression) GetVpcOk() (*VpcCondition, bool) {
	if o == nil {
		return nil, false
	}
	return o.Vpc.Get(), o.Vpc.IsSet()
}

// HasVpc returns a boolean if a field has been set.
func (o *BackupPostureControlExpression) HasVpc() bool {
	if o != nil && o.Vpc.IsSet() {
		return true
	}

	return false
}

// SetVpc gets a reference to the given NullableVpcCondition and assigns it to the Vpc field.
func (o *BackupPostureControlExpression) SetVpc(v VpcCondition) {
	o.Vpc.Set(&v)
}
// SetVpcNil sets the value for Vpc to be an explicit nil
func (o *BackupPostureControlExpression) SetVpcNil() {
	o.Vpc.Set(nil)
}

// UnsetVpc ensures that no value is present for Vpc, not even an explicit nil
func (o *BackupPostureControlExpression) UnsetVpc() {
	o.Vpc.Unset()
}

// GetSubnets returns the Subnets field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BackupPostureControlExpression) GetSubnets() SubnetsCondition {
	if o == nil || IsNil(o.Subnets.Get()) {
		var ret SubnetsCondition
		return ret
	}
	return *o.Subnets.Get()
}

// GetSubnetsOk returns a tuple with the Subnets field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BackupPostureControlExpression) GetSubnetsOk() (*SubnetsCondition, bool) {
	if o == nil {
		return nil, false
	}
	return o.Subnets.Get(), o.Subnets.IsSet()
}

// HasSubnets returns a boolean if a field has been set.
func (o *BackupPostureControlExpression) HasSubnets() bool {
	if o != nil && o.Subnets.IsSet() {
		return true
	}

	return false
}

// SetSubnets gets a reference to the given NullableSubnetsCondition and assigns it to the Subnets field.
func (o *BackupPostureControlExpression) SetSubnets(v SubnetsCondition) {
	o.Subnets.Set(&v)
}
// SetSubnetsNil sets the value for Subnets to be an explicit nil
func (o *BackupPostureControlExpression) SetSubnetsNil() {
	o.Subnets.Set(nil)
}

// UnsetSubnets ensures that no value is present for Subnets, not even an explicit nil
func (o *BackupPostureControlExpression) UnsetSubnets() {
	o.Subnets.Unset()
}

// GetResourceGroupName returns the ResourceGroupName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BackupPostureControlExpression) GetResourceGroupName() ResourceGroupNameCondition {
	if o == nil || IsNil(o.ResourceGroupName.Get()) {
		var ret ResourceGroupNameCondition
		return ret
	}
	return *o.ResourceGroupName.Get()
}

// GetResourceGroupNameOk returns a tuple with the ResourceGroupName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BackupPostureControlExpression) GetResourceGroupNameOk() (*ResourceGroupNameCondition, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResourceGroupName.Get(), o.ResourceGroupName.IsSet()
}

// HasResourceGroupName returns a boolean if a field has been set.
func (o *BackupPostureControlExpression) HasResourceGroupName() bool {
	if o != nil && o.ResourceGroupName.IsSet() {
		return true
	}

	return false
}

// SetResourceGroupName gets a reference to the given NullableResourceGroupNameCondition and assigns it to the ResourceGroupName field.
func (o *BackupPostureControlExpression) SetResourceGroupName(v ResourceGroupNameCondition) {
	o.ResourceGroupName.Set(&v)
}
// SetResourceGroupNameNil sets the value for ResourceGroupName to be an explicit nil
func (o *BackupPostureControlExpression) SetResourceGroupNameNil() {
	o.ResourceGroupName.Set(nil)
}

// UnsetResourceGroupName ensures that no value is present for ResourceGroupName, not even an explicit nil
func (o *BackupPostureControlExpression) UnsetResourceGroupName() {
	o.ResourceGroupName.Unset()
}

// GetResourceName returns the ResourceName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BackupPostureControlExpression) GetResourceName() ResourceNameCondition {
	if o == nil || IsNil(o.ResourceName.Get()) {
		var ret ResourceNameCondition
		return ret
	}
	return *o.ResourceName.Get()
}

// GetResourceNameOk returns a tuple with the ResourceName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BackupPostureControlExpression) GetResourceNameOk() (*ResourceNameCondition, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResourceName.Get(), o.ResourceName.IsSet()
}

// HasResourceName returns a boolean if a field has been set.
func (o *BackupPostureControlExpression) HasResourceName() bool {
	if o != nil && o.ResourceName.IsSet() {
		return true
	}

	return false
}

// SetResourceName gets a reference to the given NullableResourceNameCondition and assigns it to the ResourceName field.
func (o *BackupPostureControlExpression) SetResourceName(v ResourceNameCondition) {
	o.ResourceName.Set(&v)
}
// SetResourceNameNil sets the value for ResourceName to be an explicit nil
func (o *BackupPostureControlExpression) SetResourceNameNil() {
	o.ResourceName.Set(nil)
}

// UnsetResourceName ensures that no value is present for ResourceName, not even an explicit nil
func (o *BackupPostureControlExpression) UnsetResourceName() {
	o.ResourceName.Unset()
}

// GetResourceId returns the ResourceId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BackupPostureControlExpression) GetResourceId() ResourceIdCondition {
	if o == nil || IsNil(o.ResourceId.Get()) {
		var ret ResourceIdCondition
		return ret
	}
	return *o.ResourceId.Get()
}

// GetResourceIdOk returns a tuple with the ResourceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BackupPostureControlExpression) GetResourceIdOk() (*ResourceIdCondition, bool) {
	if o == nil {
		return nil, false
	}
	return o.ResourceId.Get(), o.ResourceId.IsSet()
}

// HasResourceId returns a boolean if a field has been set.
func (o *BackupPostureControlExpression) HasResourceId() bool {
	if o != nil && o.ResourceId.IsSet() {
		return true
	}

	return false
}

// SetResourceId gets a reference to the given NullableResourceIdCondition and assigns it to the ResourceId field.
func (o *BackupPostureControlExpression) SetResourceId(v ResourceIdCondition) {
	o.ResourceId.Set(&v)
}
// SetResourceIdNil sets the value for ResourceId to be an explicit nil
func (o *BackupPostureControlExpression) SetResourceIdNil() {
	o.ResourceId.Set(nil)
}

// UnsetResourceId ensures that no value is present for ResourceId, not even an explicit nil
func (o *BackupPostureControlExpression) UnsetResourceId() {
	o.ResourceId.Unset()
}

// GetTagKeys returns the TagKeys field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BackupPostureControlExpression) GetTagKeys() TagKeysCondition {
	if o == nil || IsNil(o.TagKeys.Get()) {
		var ret TagKeysCondition
		return ret
	}
	return *o.TagKeys.Get()
}

// GetTagKeysOk returns a tuple with the TagKeys field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BackupPostureControlExpression) GetTagKeysOk() (*TagKeysCondition, bool) {
	if o == nil {
		return nil, false
	}
	return o.TagKeys.Get(), o.TagKeys.IsSet()
}

// HasTagKeys returns a boolean if a field has been set.
func (o *BackupPostureControlExpression) HasTagKeys() bool {
	if o != nil && o.TagKeys.IsSet() {
		return true
	}

	return false
}

// SetTagKeys gets a reference to the given NullableTagKeysCondition and assigns it to the TagKeys field.
func (o *BackupPostureControlExpression) SetTagKeys(v TagKeysCondition) {
	o.TagKeys.Set(&v)
}
// SetTagKeysNil sets the value for TagKeys to be an explicit nil
func (o *BackupPostureControlExpression) SetTagKeysNil() {
	o.TagKeys.Set(nil)
}

// UnsetTagKeys ensures that no value is present for TagKeys, not even an explicit nil
func (o *BackupPostureControlExpression) UnsetTagKeys() {
	o.TagKeys.Unset()
}

// GetTagKeyValues returns the TagKeyValues field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BackupPostureControlExpression) GetTagKeyValues() TagKeyValuesCondition {
	if o == nil || IsNil(o.TagKeyValues.Get()) {
		var ret TagKeyValuesCondition
		return ret
	}
	return *o.TagKeyValues.Get()
}

// GetTagKeyValuesOk returns a tuple with the TagKeyValues field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BackupPostureControlExpression) GetTagKeyValuesOk() (*TagKeyValuesCondition, bool) {
	if o == nil {
		return nil, false
	}
	return o.TagKeyValues.Get(), o.TagKeyValues.IsSet()
}

// HasTagKeyValues returns a boolean if a field has been set.
func (o *BackupPostureControlExpression) HasTagKeyValues() bool {
	if o != nil && o.TagKeyValues.IsSet() {
		return true
	}

	return false
}

// SetTagKeyValues gets a reference to the given NullableTagKeyValuesCondition and assigns it to the TagKeyValues field.
func (o *BackupPostureControlExpression) SetTagKeyValues(v TagKeyValuesCondition) {
	o.TagKeyValues.Set(&v)
}
// SetTagKeyValuesNil sets the value for TagKeyValues to be an explicit nil
func (o *BackupPostureControlExpression) SetTagKeyValuesNil() {
	o.TagKeyValues.Set(nil)
}

// UnsetTagKeyValues ensures that no value is present for TagKeyValues, not even an explicit nil
func (o *BackupPostureControlExpression) UnsetTagKeyValues() {
	o.TagKeyValues.Unset()
}

func (o BackupPostureControlExpression) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BackupPostureControlExpression) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Group.IsSet() {
		toSerialize["group"] = o.Group.Get()
	}
	if o.ResourceType.IsSet() {
		toSerialize["resourceType"] = o.ResourceType.Get()
	}
	if o.DataClasses.IsSet() {
		toSerialize["dataClasses"] = o.DataClasses.Get()
	}
	if o.Environment.IsSet() {
		toSerialize["environment"] = o.Environment.Get()
	}
	if o.Apps.IsSet() {
		toSerialize["apps"] = o.Apps.Get()
	}
	if o.CloudProvider.IsSet() {
		toSerialize["cloudProvider"] = o.CloudProvider.Get()
	}
	if o.AccountId.IsSet() {
		toSerialize["accountId"] = o.AccountId.Get()
	}
	if o.SourceRegion.IsSet() {
		toSerialize["sourceRegion"] = o.SourceRegion.Get()
	}
	if o.Vpc.IsSet() {
		toSerialize["vpc"] = o.Vpc.Get()
	}
	if o.Subnets.IsSet() {
		toSerialize["subnets"] = o.Subnets.Get()
	}
	if o.ResourceGroupName.IsSet() {
		toSerialize["resourceGroupName"] = o.ResourceGroupName.Get()
	}
	if o.ResourceName.IsSet() {
		toSerialize["resourceName"] = o.ResourceName.Get()
	}
	if o.ResourceId.IsSet() {
		toSerialize["resourceId"] = o.ResourceId.Get()
	}
	if o.TagKeys.IsSet() {
		toSerialize["tagKeys"] = o.TagKeys.Get()
	}
	if o.TagKeyValues.IsSet() {
		toSerialize["tagKeyValues"] = o.TagKeyValues.Get()
	}
	return toSerialize, nil
}

type NullableBackupPostureControlExpression struct {
	value *BackupPostureControlExpression
	isSet bool
}

func (v NullableBackupPostureControlExpression) Get() *BackupPostureControlExpression {
	return v.value
}

func (v *NullableBackupPostureControlExpression) Set(val *BackupPostureControlExpression) {
	v.value = val
	v.isSet = true
}

func (v NullableBackupPostureControlExpression) IsSet() bool {
	return v.isSet
}

func (v *NullableBackupPostureControlExpression) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBackupPostureControlExpression(val *BackupPostureControlExpression) *NullableBackupPostureControlExpression {
	return &NullableBackupPostureControlExpression{value: val, isSet: true}
}

func (v NullableBackupPostureControlExpression) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBackupPostureControlExpression) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


