/*
Eon API

The Eon.io REST API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eon

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the RestoreAccountConfigInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RestoreAccountConfigInput{}

// RestoreAccountConfigInput struct for RestoreAccountConfigInput
type RestoreAccountConfigInput struct {
	CloudProvider Provider `json:"cloudProvider"`
	Aws NullableAwsRestoreAccountConfigInput `json:"aws,omitempty"`
}

type _RestoreAccountConfigInput RestoreAccountConfigInput

// NewRestoreAccountConfigInput instantiates a new RestoreAccountConfigInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRestoreAccountConfigInput(cloudProvider Provider) *RestoreAccountConfigInput {
	this := RestoreAccountConfigInput{}
	this.CloudProvider = cloudProvider
	return &this
}

// NewRestoreAccountConfigInputWithDefaults instantiates a new RestoreAccountConfigInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRestoreAccountConfigInputWithDefaults() *RestoreAccountConfigInput {
	this := RestoreAccountConfigInput{}
	return &this
}

// GetCloudProvider returns the CloudProvider field value
func (o *RestoreAccountConfigInput) GetCloudProvider() Provider {
	if o == nil {
		var ret Provider
		return ret
	}

	return o.CloudProvider
}

// GetCloudProviderOk returns a tuple with the CloudProvider field value
// and a boolean to check if the value has been set.
func (o *RestoreAccountConfigInput) GetCloudProviderOk() (*Provider, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CloudProvider, true
}

// SetCloudProvider sets field value
func (o *RestoreAccountConfigInput) SetCloudProvider(v Provider) {
	o.CloudProvider = v
}

// GetAws returns the Aws field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RestoreAccountConfigInput) GetAws() AwsRestoreAccountConfigInput {
	if o == nil || IsNil(o.Aws.Get()) {
		var ret AwsRestoreAccountConfigInput
		return ret
	}
	return *o.Aws.Get()
}

// GetAwsOk returns a tuple with the Aws field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RestoreAccountConfigInput) GetAwsOk() (*AwsRestoreAccountConfigInput, bool) {
	if o == nil {
		return nil, false
	}
	return o.Aws.Get(), o.Aws.IsSet()
}

// HasAws returns a boolean if a field has been set.
func (o *RestoreAccountConfigInput) HasAws() bool {
	if o != nil && o.Aws.IsSet() {
		return true
	}

	return false
}

// SetAws gets a reference to the given NullableAwsRestoreAccountConfigInput and assigns it to the Aws field.
func (o *RestoreAccountConfigInput) SetAws(v AwsRestoreAccountConfigInput) {
	o.Aws.Set(&v)
}
// SetAwsNil sets the value for Aws to be an explicit nil
func (o *RestoreAccountConfigInput) SetAwsNil() {
	o.Aws.Set(nil)
}

// UnsetAws ensures that no value is present for Aws, not even an explicit nil
func (o *RestoreAccountConfigInput) UnsetAws() {
	o.Aws.Unset()
}

func (o RestoreAccountConfigInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RestoreAccountConfigInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cloudProvider"] = o.CloudProvider
	if o.Aws.IsSet() {
		toSerialize["aws"] = o.Aws.Get()
	}
	return toSerialize, nil
}

func (o *RestoreAccountConfigInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"cloudProvider",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRestoreAccountConfigInput := _RestoreAccountConfigInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varRestoreAccountConfigInput)

	if err != nil {
		return err
	}

	*o = RestoreAccountConfigInput(varRestoreAccountConfigInput)

	return err
}

type NullableRestoreAccountConfigInput struct {
	value *RestoreAccountConfigInput
	isSet bool
}

func (v NullableRestoreAccountConfigInput) Get() *RestoreAccountConfigInput {
	return v.value
}

func (v *NullableRestoreAccountConfigInput) Set(val *RestoreAccountConfigInput) {
	v.value = val
	v.isSet = true
}

func (v NullableRestoreAccountConfigInput) IsSet() bool {
	return v.isSet
}

func (v *NullableRestoreAccountConfigInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRestoreAccountConfigInput(val *RestoreAccountConfigInput) *NullableRestoreAccountConfigInput {
	return &NullableRestoreAccountConfigInput{value: val, isSet: true}
}

func (v NullableRestoreAccountConfigInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRestoreAccountConfigInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


