/*
Eon API

The Eon.io REST API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eon

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateIdpGroupRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateIdpGroupRequest{}

// CreateIdpGroupRequest struct for CreateIdpGroupRequest
type CreateIdpGroupRequest struct {
	// The ID of the Identity Provider this group belongs to.
	IdpId string `json:"idpId"`
	// The group identifier from the Identity Provider.
	ProviderGroupId string `json:"providerGroupId"`
	// List of role IDs to assign to this IDP group.
	RoleIds []string `json:"roleIds"`
}

type _CreateIdpGroupRequest CreateIdpGroupRequest

// NewCreateIdpGroupRequest instantiates a new CreateIdpGroupRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateIdpGroupRequest(idpId string, providerGroupId string, roleIds []string) *CreateIdpGroupRequest {
	this := CreateIdpGroupRequest{}
	this.IdpId = idpId
	this.ProviderGroupId = providerGroupId
	this.RoleIds = roleIds
	return &this
}

// NewCreateIdpGroupRequestWithDefaults instantiates a new CreateIdpGroupRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateIdpGroupRequestWithDefaults() *CreateIdpGroupRequest {
	this := CreateIdpGroupRequest{}
	return &this
}

// GetIdpId returns the IdpId field value
func (o *CreateIdpGroupRequest) GetIdpId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.IdpId
}

// GetIdpIdOk returns a tuple with the IdpId field value
// and a boolean to check if the value has been set.
func (o *CreateIdpGroupRequest) GetIdpIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IdpId, true
}

// SetIdpId sets field value
func (o *CreateIdpGroupRequest) SetIdpId(v string) {
	o.IdpId = v
}

// GetProviderGroupId returns the ProviderGroupId field value
func (o *CreateIdpGroupRequest) GetProviderGroupId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProviderGroupId
}

// GetProviderGroupIdOk returns a tuple with the ProviderGroupId field value
// and a boolean to check if the value has been set.
func (o *CreateIdpGroupRequest) GetProviderGroupIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProviderGroupId, true
}

// SetProviderGroupId sets field value
func (o *CreateIdpGroupRequest) SetProviderGroupId(v string) {
	o.ProviderGroupId = v
}

// GetRoleIds returns the RoleIds field value
func (o *CreateIdpGroupRequest) GetRoleIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.RoleIds
}

// GetRoleIdsOk returns a tuple with the RoleIds field value
// and a boolean to check if the value has been set.
func (o *CreateIdpGroupRequest) GetRoleIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RoleIds, true
}

// SetRoleIds sets field value
func (o *CreateIdpGroupRequest) SetRoleIds(v []string) {
	o.RoleIds = v
}

func (o CreateIdpGroupRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateIdpGroupRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["idpId"] = o.IdpId
	toSerialize["providerGroupId"] = o.ProviderGroupId
	toSerialize["roleIds"] = o.RoleIds
	return toSerialize, nil
}

func (o *CreateIdpGroupRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"idpId",
		"providerGroupId",
		"roleIds",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateIdpGroupRequest := _CreateIdpGroupRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateIdpGroupRequest)

	if err != nil {
		return err
	}

	*o = CreateIdpGroupRequest(varCreateIdpGroupRequest)

	return err
}

type NullableCreateIdpGroupRequest struct {
	value *CreateIdpGroupRequest
	isSet bool
}

func (v NullableCreateIdpGroupRequest) Get() *CreateIdpGroupRequest {
	return v.value
}

func (v *NullableCreateIdpGroupRequest) Set(val *CreateIdpGroupRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateIdpGroupRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateIdpGroupRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateIdpGroupRequest(val *CreateIdpGroupRequest) *NullableCreateIdpGroupRequest {
	return &NullableCreateIdpGroupRequest{value: val, isSet: true}
}

func (v NullableCreateIdpGroupRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateIdpGroupRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


