/*
Eon API

The Eon.io REST API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eon

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the VaultProviderAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VaultProviderAttributes{}

// VaultProviderAttributes Cloud-provider-specific vault attributes. 
type VaultProviderAttributes struct {
	CloudProvider Provider `json:"cloudProvider"`
	Aws NullableAwsVaultConfig `json:"aws,omitempty"`
}

type _VaultProviderAttributes VaultProviderAttributes

// NewVaultProviderAttributes instantiates a new VaultProviderAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVaultProviderAttributes(cloudProvider Provider) *VaultProviderAttributes {
	this := VaultProviderAttributes{}
	this.CloudProvider = cloudProvider
	return &this
}

// NewVaultProviderAttributesWithDefaults instantiates a new VaultProviderAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVaultProviderAttributesWithDefaults() *VaultProviderAttributes {
	this := VaultProviderAttributes{}
	return &this
}

// GetCloudProvider returns the CloudProvider field value
func (o *VaultProviderAttributes) GetCloudProvider() Provider {
	if o == nil {
		var ret Provider
		return ret
	}

	return o.CloudProvider
}

// GetCloudProviderOk returns a tuple with the CloudProvider field value
// and a boolean to check if the value has been set.
func (o *VaultProviderAttributes) GetCloudProviderOk() (*Provider, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CloudProvider, true
}

// SetCloudProvider sets field value
func (o *VaultProviderAttributes) SetCloudProvider(v Provider) {
	o.CloudProvider = v
}

// GetAws returns the Aws field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *VaultProviderAttributes) GetAws() AwsVaultConfig {
	if o == nil || IsNil(o.Aws.Get()) {
		var ret AwsVaultConfig
		return ret
	}
	return *o.Aws.Get()
}

// GetAwsOk returns a tuple with the Aws field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *VaultProviderAttributes) GetAwsOk() (*AwsVaultConfig, bool) {
	if o == nil {
		return nil, false
	}
	return o.Aws.Get(), o.Aws.IsSet()
}

// HasAws returns a boolean if a field has been set.
func (o *VaultProviderAttributes) HasAws() bool {
	if o != nil && o.Aws.IsSet() {
		return true
	}

	return false
}

// SetAws gets a reference to the given NullableAwsVaultConfig and assigns it to the Aws field.
func (o *VaultProviderAttributes) SetAws(v AwsVaultConfig) {
	o.Aws.Set(&v)
}
// SetAwsNil sets the value for Aws to be an explicit nil
func (o *VaultProviderAttributes) SetAwsNil() {
	o.Aws.Set(nil)
}

// UnsetAws ensures that no value is present for Aws, not even an explicit nil
func (o *VaultProviderAttributes) UnsetAws() {
	o.Aws.Unset()
}

func (o VaultProviderAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VaultProviderAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cloudProvider"] = o.CloudProvider
	if o.Aws.IsSet() {
		toSerialize["aws"] = o.Aws.Get()
	}
	return toSerialize, nil
}

func (o *VaultProviderAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"cloudProvider",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVaultProviderAttributes := _VaultProviderAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varVaultProviderAttributes)

	if err != nil {
		return err
	}

	*o = VaultProviderAttributes(varVaultProviderAttributes)

	return err
}

type NullableVaultProviderAttributes struct {
	value *VaultProviderAttributes
	isSet bool
}

func (v NullableVaultProviderAttributes) Get() *VaultProviderAttributes {
	return v.value
}

func (v *NullableVaultProviderAttributes) Set(val *VaultProviderAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableVaultProviderAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableVaultProviderAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVaultProviderAttributes(val *VaultProviderAttributes) *NullableVaultProviderAttributes {
	return &NullableVaultProviderAttributes{value: val, isSet: true}
}

func (v NullableVaultProviderAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVaultProviderAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


