/*
Eon API

The Eon.io REST API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eon

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AwsRestoreAccountAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AwsRestoreAccountAttributes{}

// AwsRestoreAccountAttributes struct for AwsRestoreAccountAttributes
type AwsRestoreAccountAttributes struct {
	// ARN of the role Eon assumes to access the account in AWS.
	RoleArn string `json:"roleArn"`
	// Cloud-provider-assigned ID of the AWS organization the account belongs to.
	OrganizationId *string `json:"organizationId,omitempty"`
}

type _AwsRestoreAccountAttributes AwsRestoreAccountAttributes

// NewAwsRestoreAccountAttributes instantiates a new AwsRestoreAccountAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAwsRestoreAccountAttributes(roleArn string) *AwsRestoreAccountAttributes {
	this := AwsRestoreAccountAttributes{}
	this.RoleArn = roleArn
	return &this
}

// NewAwsRestoreAccountAttributesWithDefaults instantiates a new AwsRestoreAccountAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAwsRestoreAccountAttributesWithDefaults() *AwsRestoreAccountAttributes {
	this := AwsRestoreAccountAttributes{}
	return &this
}

// GetRoleArn returns the RoleArn field value
func (o *AwsRestoreAccountAttributes) GetRoleArn() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RoleArn
}

// GetRoleArnOk returns a tuple with the RoleArn field value
// and a boolean to check if the value has been set.
func (o *AwsRestoreAccountAttributes) GetRoleArnOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RoleArn, true
}

// SetRoleArn sets field value
func (o *AwsRestoreAccountAttributes) SetRoleArn(v string) {
	o.RoleArn = v
}

// GetOrganizationId returns the OrganizationId field value if set, zero value otherwise.
func (o *AwsRestoreAccountAttributes) GetOrganizationId() string {
	if o == nil || IsNil(o.OrganizationId) {
		var ret string
		return ret
	}
	return *o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AwsRestoreAccountAttributes) GetOrganizationIdOk() (*string, bool) {
	if o == nil || IsNil(o.OrganizationId) {
		return nil, false
	}
	return o.OrganizationId, true
}

// HasOrganizationId returns a boolean if a field has been set.
func (o *AwsRestoreAccountAttributes) HasOrganizationId() bool {
	if o != nil && !IsNil(o.OrganizationId) {
		return true
	}

	return false
}

// SetOrganizationId gets a reference to the given string and assigns it to the OrganizationId field.
func (o *AwsRestoreAccountAttributes) SetOrganizationId(v string) {
	o.OrganizationId = &v
}

func (o AwsRestoreAccountAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AwsRestoreAccountAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["roleArn"] = o.RoleArn
	if !IsNil(o.OrganizationId) {
		toSerialize["organizationId"] = o.OrganizationId
	}
	return toSerialize, nil
}

func (o *AwsRestoreAccountAttributes) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"roleArn",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAwsRestoreAccountAttributes := _AwsRestoreAccountAttributes{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAwsRestoreAccountAttributes)

	if err != nil {
		return err
	}

	*o = AwsRestoreAccountAttributes(varAwsRestoreAccountAttributes)

	return err
}

type NullableAwsRestoreAccountAttributes struct {
	value *AwsRestoreAccountAttributes
	isSet bool
}

func (v NullableAwsRestoreAccountAttributes) Get() *AwsRestoreAccountAttributes {
	return v.value
}

func (v *NullableAwsRestoreAccountAttributes) Set(val *AwsRestoreAccountAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableAwsRestoreAccountAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableAwsRestoreAccountAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAwsRestoreAccountAttributes(val *AwsRestoreAccountAttributes) *NullableAwsRestoreAccountAttributes {
	return &NullableAwsRestoreAccountAttributes{value: val, isSet: true}
}

func (v NullableAwsRestoreAccountAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAwsRestoreAccountAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


