/*
Eon API

The Eon.io REST API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eon

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the QueryCostDataResponseRecordsInnerCostsInnerUsage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QueryCostDataResponseRecordsInnerCostsInnerUsage{}

// QueryCostDataResponseRecordsInnerCostsInnerUsage Resource usage information
type QueryCostDataResponseRecordsInnerCostsInnerUsage struct {
	// Raw usage amount for the resource
	Amount float64 `json:"amount"`
	// Unit of measurement for usage
	Unit string `json:"unit"`
}

type _QueryCostDataResponseRecordsInnerCostsInnerUsage QueryCostDataResponseRecordsInnerCostsInnerUsage

// NewQueryCostDataResponseRecordsInnerCostsInnerUsage instantiates a new QueryCostDataResponseRecordsInnerCostsInnerUsage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQueryCostDataResponseRecordsInnerCostsInnerUsage(amount float64, unit string) *QueryCostDataResponseRecordsInnerCostsInnerUsage {
	this := QueryCostDataResponseRecordsInnerCostsInnerUsage{}
	this.Amount = amount
	this.Unit = unit
	return &this
}

// NewQueryCostDataResponseRecordsInnerCostsInnerUsageWithDefaults instantiates a new QueryCostDataResponseRecordsInnerCostsInnerUsage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQueryCostDataResponseRecordsInnerCostsInnerUsageWithDefaults() *QueryCostDataResponseRecordsInnerCostsInnerUsage {
	this := QueryCostDataResponseRecordsInnerCostsInnerUsage{}
	return &this
}

// GetAmount returns the Amount field value
func (o *QueryCostDataResponseRecordsInnerCostsInnerUsage) GetAmount() float64 {
	if o == nil {
		var ret float64
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *QueryCostDataResponseRecordsInnerCostsInnerUsage) GetAmountOk() (*float64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *QueryCostDataResponseRecordsInnerCostsInnerUsage) SetAmount(v float64) {
	o.Amount = v
}

// GetUnit returns the Unit field value
func (o *QueryCostDataResponseRecordsInnerCostsInnerUsage) GetUnit() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Unit
}

// GetUnitOk returns a tuple with the Unit field value
// and a boolean to check if the value has been set.
func (o *QueryCostDataResponseRecordsInnerCostsInnerUsage) GetUnitOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Unit, true
}

// SetUnit sets field value
func (o *QueryCostDataResponseRecordsInnerCostsInnerUsage) SetUnit(v string) {
	o.Unit = v
}

func (o QueryCostDataResponseRecordsInnerCostsInnerUsage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QueryCostDataResponseRecordsInnerCostsInnerUsage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["amount"] = o.Amount
	toSerialize["unit"] = o.Unit
	return toSerialize, nil
}

func (o *QueryCostDataResponseRecordsInnerCostsInnerUsage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"amount",
		"unit",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQueryCostDataResponseRecordsInnerCostsInnerUsage := _QueryCostDataResponseRecordsInnerCostsInnerUsage{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varQueryCostDataResponseRecordsInnerCostsInnerUsage)

	if err != nil {
		return err
	}

	*o = QueryCostDataResponseRecordsInnerCostsInnerUsage(varQueryCostDataResponseRecordsInnerCostsInnerUsage)

	return err
}

type NullableQueryCostDataResponseRecordsInnerCostsInnerUsage struct {
	value *QueryCostDataResponseRecordsInnerCostsInnerUsage
	isSet bool
}

func (v NullableQueryCostDataResponseRecordsInnerCostsInnerUsage) Get() *QueryCostDataResponseRecordsInnerCostsInnerUsage {
	return v.value
}

func (v *NullableQueryCostDataResponseRecordsInnerCostsInnerUsage) Set(val *QueryCostDataResponseRecordsInnerCostsInnerUsage) {
	v.value = val
	v.isSet = true
}

func (v NullableQueryCostDataResponseRecordsInnerCostsInnerUsage) IsSet() bool {
	return v.isSet
}

func (v *NullableQueryCostDataResponseRecordsInnerCostsInnerUsage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQueryCostDataResponseRecordsInnerCostsInnerUsage(val *QueryCostDataResponseRecordsInnerCostsInnerUsage) *NullableQueryCostDataResponseRecordsInnerCostsInnerUsage {
	return &NullableQueryCostDataResponseRecordsInnerCostsInnerUsage{value: val, isSet: true}
}

func (v NullableQueryCostDataResponseRecordsInnerCostsInnerUsage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQueryCostDataResponseRecordsInnerCostsInnerUsage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


