/*
Eon API

The Eon.io REST API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eon

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PermissionGrantInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PermissionGrantInput{}

// PermissionGrantInput struct for PermissionGrantInput
type PermissionGrantInput struct {
	Permission PermissionType `json:"permission"`
	// If present, the ID of the set of access conditions that restrict the resources the permission is granted for. The ID must be present in an entry in `accessConditions`, and the permission itself must support access conditions. If omitted, the permission is granted for all resources. 
	AccessConditionId *string `json:"accessConditionId,omitempty"`
}

type _PermissionGrantInput PermissionGrantInput

// NewPermissionGrantInput instantiates a new PermissionGrantInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPermissionGrantInput(permission PermissionType) *PermissionGrantInput {
	this := PermissionGrantInput{}
	this.Permission = permission
	return &this
}

// NewPermissionGrantInputWithDefaults instantiates a new PermissionGrantInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPermissionGrantInputWithDefaults() *PermissionGrantInput {
	this := PermissionGrantInput{}
	return &this
}

// GetPermission returns the Permission field value
func (o *PermissionGrantInput) GetPermission() PermissionType {
	if o == nil {
		var ret PermissionType
		return ret
	}

	return o.Permission
}

// GetPermissionOk returns a tuple with the Permission field value
// and a boolean to check if the value has been set.
func (o *PermissionGrantInput) GetPermissionOk() (*PermissionType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Permission, true
}

// SetPermission sets field value
func (o *PermissionGrantInput) SetPermission(v PermissionType) {
	o.Permission = v
}

// GetAccessConditionId returns the AccessConditionId field value if set, zero value otherwise.
func (o *PermissionGrantInput) GetAccessConditionId() string {
	if o == nil || IsNil(o.AccessConditionId) {
		var ret string
		return ret
	}
	return *o.AccessConditionId
}

// GetAccessConditionIdOk returns a tuple with the AccessConditionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PermissionGrantInput) GetAccessConditionIdOk() (*string, bool) {
	if o == nil || IsNil(o.AccessConditionId) {
		return nil, false
	}
	return o.AccessConditionId, true
}

// HasAccessConditionId returns a boolean if a field has been set.
func (o *PermissionGrantInput) HasAccessConditionId() bool {
	if o != nil && !IsNil(o.AccessConditionId) {
		return true
	}

	return false
}

// SetAccessConditionId gets a reference to the given string and assigns it to the AccessConditionId field.
func (o *PermissionGrantInput) SetAccessConditionId(v string) {
	o.AccessConditionId = &v
}

func (o PermissionGrantInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PermissionGrantInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["permission"] = o.Permission
	if !IsNil(o.AccessConditionId) {
		toSerialize["accessConditionId"] = o.AccessConditionId
	}
	return toSerialize, nil
}

func (o *PermissionGrantInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"permission",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPermissionGrantInput := _PermissionGrantInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPermissionGrantInput)

	if err != nil {
		return err
	}

	*o = PermissionGrantInput(varPermissionGrantInput)

	return err
}

type NullablePermissionGrantInput struct {
	value *PermissionGrantInput
	isSet bool
}

func (v NullablePermissionGrantInput) Get() *PermissionGrantInput {
	return v.value
}

func (v *NullablePermissionGrantInput) Set(val *PermissionGrantInput) {
	v.value = val
	v.isSet = true
}

func (v NullablePermissionGrantInput) IsSet() bool {
	return v.isSet
}

func (v *NullablePermissionGrantInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePermissionGrantInput(val *PermissionGrantInput) *NullablePermissionGrantInput {
	return &NullablePermissionGrantInput{value: val, isSet: true}
}

func (v NullablePermissionGrantInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePermissionGrantInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


