/*
Eon API

The Eon.io REST API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package eon

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DisconnectRestoreAccountResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DisconnectRestoreAccountResponse{}

// DisconnectRestoreAccountResponse struct for DisconnectRestoreAccountResponse
type DisconnectRestoreAccountResponse struct {
	RestoreAccount RestoreAccount `json:"restoreAccount"`
}

type _DisconnectRestoreAccountResponse DisconnectRestoreAccountResponse

// NewDisconnectRestoreAccountResponse instantiates a new DisconnectRestoreAccountResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDisconnectRestoreAccountResponse(restoreAccount RestoreAccount) *DisconnectRestoreAccountResponse {
	this := DisconnectRestoreAccountResponse{}
	this.RestoreAccount = restoreAccount
	return &this
}

// NewDisconnectRestoreAccountResponseWithDefaults instantiates a new DisconnectRestoreAccountResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDisconnectRestoreAccountResponseWithDefaults() *DisconnectRestoreAccountResponse {
	this := DisconnectRestoreAccountResponse{}
	return &this
}

// GetRestoreAccount returns the RestoreAccount field value
func (o *DisconnectRestoreAccountResponse) GetRestoreAccount() RestoreAccount {
	if o == nil {
		var ret RestoreAccount
		return ret
	}

	return o.RestoreAccount
}

// GetRestoreAccountOk returns a tuple with the RestoreAccount field value
// and a boolean to check if the value has been set.
func (o *DisconnectRestoreAccountResponse) GetRestoreAccountOk() (*RestoreAccount, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RestoreAccount, true
}

// SetRestoreAccount sets field value
func (o *DisconnectRestoreAccountResponse) SetRestoreAccount(v RestoreAccount) {
	o.RestoreAccount = v
}

func (o DisconnectRestoreAccountResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DisconnectRestoreAccountResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["restoreAccount"] = o.RestoreAccount
	return toSerialize, nil
}

func (o *DisconnectRestoreAccountResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"restoreAccount",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDisconnectRestoreAccountResponse := _DisconnectRestoreAccountResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	//decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDisconnectRestoreAccountResponse)

	if err != nil {
		return err
	}

	*o = DisconnectRestoreAccountResponse(varDisconnectRestoreAccountResponse)

	return err
}

type NullableDisconnectRestoreAccountResponse struct {
	value *DisconnectRestoreAccountResponse
	isSet bool
}

func (v NullableDisconnectRestoreAccountResponse) Get() *DisconnectRestoreAccountResponse {
	return v.value
}

func (v *NullableDisconnectRestoreAccountResponse) Set(val *DisconnectRestoreAccountResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDisconnectRestoreAccountResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDisconnectRestoreAccountResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDisconnectRestoreAccountResponse(val *DisconnectRestoreAccountResponse) *NullableDisconnectRestoreAccountResponse {
	return &NullableDisconnectRestoreAccountResponse{value: val, isSet: true}
}

func (v NullableDisconnectRestoreAccountResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDisconnectRestoreAccountResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


